"use client";

import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import { formatIsoDateShort } from "@/lib/hr/schedules";
import { loadPayslipPdfLogo } from "@/lib/hr/payslip-pdf";

export type AttendanceValidationPdfEmployee = {
  fullName: string;
  empNo: string;
  departmentName: string | null;
  positionName: string | null;
  joiningDate: string | null;
  terminationDate: string | null;
};

export type AttendanceValidationPdfRow = {
  workDate: string;
  rosterLabel: string;
  scheduleTime: string;
  clockIn: string;
  clockOut: string;
  hours: string;
  issue: string;
  approvalStatus: string;
  /** Public holiday date — purple date styling. */
  isPublicHoliday?: boolean;
};

export type ExportAttendanceValidationPdfOptions = {
  venueName: string;
  venueLogoUrl?: string | null;
  periodLabel: string;
  employee: AttendanceValidationPdfEmployee;
  rows: AttendanceValidationPdfRow[];
  exportedAt: Date;
  userDisplayName: string;
};

const BRAND_DARK: [number, number, number] = [61, 66, 31];
const HEADER_BG: [number, number, number] = [240, 243, 221];
const PH_HEADER_TEXT: [number, number, number] = [91, 33, 182];
const FOOTER_TEXT: [number, number, number] = [110, 110, 110];
const RULE_COLOR: [number, number, number] = [61, 66, 31];
const META_LABEL: [number, number, number] = [80, 80, 80];

function sanitizeFilenamePart(value: string): string {
  return value
    .trim()
    .replace(/[\\/:*?"<>|]/g, "")
    .replace(/\s+/g, " ");
}

function formatExportDateStamp(date: Date): string {
  const day = String(date.getDate()).padStart(2, "0");
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const year = String(date.getFullYear()).slice(-2);
  return `${day}-${month}-${year}`;
}

function formatExportTimestamp(date: Date): string {
  const day = String(date.getDate()).padStart(2, "0");
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const year = date.getFullYear();
  const hours = String(date.getHours()).padStart(2, "0");
  const minutes = String(date.getMinutes()).padStart(2, "0");
  return `${day}/${month}/${year} ${hours}:${minutes}`;
}

/** Same HR export footer line as Schedules PDF. */
function buildInternalDocumentLine(
  exportedAt: Date,
  userDisplayName: string,
): string {
  const name = userDisplayName.trim() || "Unknown";
  return `File created on: ${formatExportTimestamp(exportedAt)} — Generated by ${name}   |   Internal document`;
}

function pdfSafeText(value: string): string {
  return value.replace(/[^\x20-\x7E]/g, "?");
}

export function buildAttendanceValidationPdfFilename(input: {
  venueName: string;
  empNo: string;
  fullName: string;
  exportedAt?: Date;
}): string {
  const venue = sanitizeFilenamePart(input.venueName);
  const emp = sanitizeFilenamePart(input.empNo);
  const name = sanitizeFilenamePart(input.fullName);
  const stamp = formatExportDateStamp(input.exportedAt ?? new Date());
  return `${venue} Attendance Validation - ${name} (${emp}) ${stamp}.pdf`;
}

function drawPageHeader(
  doc: jsPDF,
  options: {
    venueName: string;
    periodLabel: string;
  },
  logo: Awaited<ReturnType<typeof loadPayslipPdfLogo>>,
  marginLeft: number,
  marginRight: number,
): number {
  const pageWidth = doc.internal.pageSize.getWidth();
  const logoGap = 3;
  const logoMaxWidth = 30;
  const logoHeight = 7.5;
  let textLeft = marginLeft;
  let textBaseline = 10;

  if (logo && logo.width > 0 && logo.height > 0) {
    const logoWidth = Math.min(
      logoMaxWidth,
      (logo.width / logo.height) * logoHeight,
    );
    const renderedLogoHeight = logoWidth / (logo.width / logo.height);
    doc.addImage(
      logo.dataUrl,
      logo.format,
      marginLeft,
      7.5,
      logoWidth,
      renderedLogoHeight,
      undefined,
      "FAST",
    );
    textLeft = marginLeft + logoWidth + logoGap;
  }

  doc.setFont("times", "bold");
  doc.setFontSize(13);
  doc.setTextColor(...BRAND_DARK);
  doc.text(pdfSafeText(options.venueName), textLeft, textBaseline);
  textBaseline += 4.5;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(9.5);
  doc.setTextColor(...BRAND_DARK);
  doc.text("Attendance Validation", textLeft, textBaseline);
  textBaseline += 4;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(72, 78, 42);
  doc.text(pdfSafeText(options.periodLabel), textLeft, textBaseline);

  const ruleY = Math.max(
    logo ? 7.5 + logoHeight + 1.5 : 0,
    textBaseline + 2.5,
  );
  doc.setDrawColor(...RULE_COLOR);
  doc.setLineWidth(0.4);
  doc.line(marginLeft, ruleY, pageWidth - marginRight, ruleY);

  return Math.max(22, ruleY + 3);
}

function drawEmployeeDetails(
  doc: jsPDF,
  employee: AttendanceValidationPdfEmployee,
  startY: number,
  marginLeft: number,
  marginRight: number,
): number {
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = startY;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(...BRAND_DARK);
  doc.text("Employee details", marginLeft, y);
  y += 4.5;

  const pairs: Array<[string, string]> = [
    ["Name", employee.fullName.trim() || "—"],
    ["Emp no", employee.empNo.trim() || "—"],
    ["Department", employee.departmentName?.trim() || "—"],
    ["Position", employee.positionName?.trim() || "—"],
    [
      "Joining date",
      employee.joiningDate ? formatIsoDateShort(employee.joiningDate) : "—",
    ],
    [
      "Termination",
      employee.terminationDate
        ? formatIsoDateShort(employee.terminationDate)
        : "—",
    ],
  ];

  const colGap = 6;
  const usable = pageWidth - marginLeft - marginRight;
  const colWidth = (usable - colGap) / 2;
  const rowH = 4.2;
  const labelW = 28;

  doc.setFontSize(7.5);
  for (let i = 0; i < pairs.length; i += 2) {
    const left = pairs[i]!;
    const right = pairs[i + 1];
    const rowY = y + (i / 2) * rowH;

    doc.setFont("helvetica", "bold");
    doc.setTextColor(...META_LABEL);
    doc.text(left[0], marginLeft, rowY);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...BRAND_DARK);
    doc.text(
      pdfSafeText(left[1]),
      marginLeft + labelW,
      rowY,
      { maxWidth: colWidth - labelW },
    );

    if (right) {
      const rightX = marginLeft + colWidth + colGap;
      doc.setFont("helvetica", "bold");
      doc.setTextColor(...META_LABEL);
      doc.text(right[0], rightX, rowY);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(...BRAND_DARK);
      doc.text(
        pdfSafeText(right[1]),
        rightX + labelW,
        rowY,
        { maxWidth: colWidth - labelW },
      );
    }
  }

  y += Math.ceil(pairs.length / 2) * rowH + 2;
  doc.setDrawColor(220, 220, 220);
  doc.setLineWidth(0.15);
  doc.line(marginLeft, y, pageWidth - marginRight, y);
  return y + 3;
}

function drawPageFooter(
  doc: jsPDF,
  exportedAt: Date,
  userDisplayName: string,
  marginLeft: number,
  marginRight: number,
) {
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const footerY = pageHeight - 6;

  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.2);
  doc.line(marginLeft, footerY - 3, pageWidth - marginRight, footerY - 3);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(6.5);
  doc.setTextColor(...FOOTER_TEXT);
  doc.text(
    buildInternalDocumentLine(exportedAt, userDisplayName),
    pageWidth / 2,
    footerY,
    { align: "center" },
  );
}

/** Generate and download the current Validation table view as PDF. */
export async function exportAttendanceValidationPdf(
  options: ExportAttendanceValidationPdfOptions,
): Promise<void> {
  if (options.rows.length === 0) {
    throw new Error("No validation rows to export.");
  }

  const doc = new jsPDF({
    orientation: "landscape",
    unit: "mm",
    format: "a4",
  });
  const margin = { left: 10, right: 10, top: 10, bottom: 12 };
  const logo = options.venueLogoUrl
    ? await loadPayslipPdfLogo(options.venueLogoUrl)
    : null;

  let y = drawPageHeader(
    doc,
    {
      venueName: options.venueName,
      periodLabel: options.periodLabel,
    },
    logo,
    margin.left,
    margin.right,
  );
  y = drawEmployeeDetails(
    doc,
    options.employee,
    y,
    margin.left,
    margin.right,
  );

  const holidayFlags = options.rows.map((r) => Boolean(r.isPublicHoliday));

  autoTable(doc, {
    startY: y,
    margin: {
      left: margin.left,
      right: margin.right,
      top: margin.top + 12,
      bottom: margin.bottom,
    },
    head: [
      [
        "Date",
        "Roster",
        "Schedule",
        "Clock in",
        "Clock out",
        "Hours",
        "Issue",
        "Status",
      ],
    ],
    body: options.rows.map((row) => [
      formatIsoDateShort(row.workDate),
      pdfSafeText(row.rosterLabel || "—"),
      pdfSafeText(row.scheduleTime || "—"),
      pdfSafeText(row.clockIn || "—"),
      pdfSafeText(row.clockOut || "—"),
      pdfSafeText(row.hours || "—"),
      pdfSafeText(row.issue || "—"),
      pdfSafeText(row.approvalStatus || "—"),
    ]),
    styles: {
      font: "helvetica",
      fontSize: 7,
      cellPadding: 1.2,
      textColor: BRAND_DARK,
      lineColor: [220, 220, 220],
      lineWidth: 0.1,
      overflow: "linebreak",
      valign: "middle",
    },
    headStyles: {
      fillColor: HEADER_BG,
      textColor: BRAND_DARK,
      fontStyle: "bold",
      fontSize: 7,
    },
    columnStyles: {
      0: { cellWidth: 22 },
      1: { cellWidth: 18 },
      2: { cellWidth: 28 },
      3: { cellWidth: 20 },
      4: { cellWidth: 20 },
      5: { cellWidth: 14 },
      6: { cellWidth: "auto" },
      7: { cellWidth: 22 },
    },
    didParseCell(data) {
      if (data.section !== "body" || data.column.index !== 0) return;
      if (holidayFlags[data.row.index]) {
        data.cell.styles.textColor = PH_HEADER_TEXT;
        data.cell.styles.fontStyle = "bold";
      }
    },
    didDrawPage() {
      drawPageFooter(
        doc,
        options.exportedAt,
        options.userDisplayName,
        margin.left,
        margin.right,
      );
    },
  });

  doc.save(
    buildAttendanceValidationPdfFilename({
      venueName: options.venueName,
      empNo: options.employee.empNo,
      fullName: options.employee.fullName,
      exportedAt: options.exportedAt,
    }),
  );
}
