"use client";

import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import { loadPayslipPdfLogo } from "@/lib/hr/payslip-pdf";

export type AttendanceInsightsPdfStaffRow = {
  empNo: string;
  fullName: string;
  employmentStatus: string | null;
  workingStatus: string | null;
  dayCount: number;
  completeDayCount: number;
  totalHours: number;
  punchCompletePct: number | null;
};

export type AttendanceInsightsPdfDepartmentGroup = {
  departmentName: string;
  rows: AttendanceInsightsPdfStaffRow[];
  totalHours: number;
  dayCount: number;
  completeDayCount: number;
  punchCompletePct: number;
};

export type AttendanceInsightsPdfDepartmentScore = {
  departmentName: string;
  staffCount: number;
  dayCount: number;
  completeDayCount: number;
  punchCompletePct: number;
};

export type ExportAttendanceInsightsPdfOptions = {
  venueName: string;
  venueLogoUrl?: string | null;
  periodLabel: string;
  fromDate: string;
  toDate: string;
  summaryLine: string;
  groups: AttendanceInsightsPdfDepartmentGroup[];
  departmentScores: AttendanceInsightsPdfDepartmentScore[];
  exportedAt: Date;
  userDisplayName: string;
};

const BRAND_DARK: [number, number, number] = [61, 66, 31];
const HEADER_BG: [number, number, number] = [240, 243, 221];
const DEPT_BAND_BG: [number, number, number] = [226, 232, 200];
const TOTALS_BG: [number, number, number] = [248, 249, 244];
const FOOTER_TEXT: [number, number, number] = [110, 110, 110];
const RULE_COLOR: [number, number, number] = [61, 66, 31];
const PUNCH_GOOD: [number, number, number] = [6, 95, 70];
const PUNCH_OK: [number, number, number] = [120, 53, 15];
const PUNCH_LOW: [number, number, number] = [159, 18, 57];

function sanitizeFilenamePart(value: string): string {
  return value
    .trim()
    .replace(/[\\/:*?"<>|]/g, "")
    .replace(/\s+/g, " ");
}

function formatExportDateStamp(date: Date): string {
  const day = String(date.getDate()).padStart(2, "0");
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const year = String(date.getFullYear()).slice(-2);
  return `${day}-${month}-${year}`;
}

function formatExportTimestamp(date: Date): string {
  const day = String(date.getDate()).padStart(2, "0");
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const year = date.getFullYear();
  const hours = String(date.getHours()).padStart(2, "0");
  const minutes = String(date.getMinutes()).padStart(2, "0");
  return `${day}/${month}/${year} ${hours}:${minutes}`;
}

function buildInternalDocumentLine(
  exportedAt: Date,
  userDisplayName: string,
): string {
  const name = userDisplayName.trim() || "Unknown";
  return `File created on: ${formatExportTimestamp(exportedAt)} — Generated by ${name}   |   Internal document`;
}

function pdfSafeText(value: string): string {
  return value
    .replace(/[\u2013\u2014\u2212]/g, "-")
    .replace(/[\u00B7\u2022]/g, "|")
    .replace(/[^\x20-\x7E]/g, "?");
}

function formatHours(hours: number): string {
  return hours.toFixed(2);
}

function formatPct(pct: number): string {
  return `${Math.round(pct)}%`;
}

function punchPctColor(pct: number): [number, number, number] {
  if (pct >= 95) return PUNCH_GOOD;
  if (pct >= 80) return PUNCH_OK;
  return PUNCH_LOW;
}

function shiftDaysLabel(complete: number, total: number): string {
  if (total === 0) return "-";
  return `${complete}/${total}`;
}

export function buildAttendanceInsightsPdfFilename(input: {
  venueName: string;
  fromDate: string;
  toDate: string;
  exportedAt?: Date;
}): string {
  const venue = sanitizeFilenamePart(input.venueName);
  const from = sanitizeFilenamePart(input.fromDate);
  const to = sanitizeFilenamePart(input.toDate);
  const stamp = formatExportDateStamp(input.exportedAt ?? new Date());
  return `${venue} Attendance Insights ${from} to ${to} ${stamp}.pdf`;
}

function drawPageHeader(
  doc: jsPDF,
  options: { venueName: string; periodLabel: string },
  logo: Awaited<ReturnType<typeof loadPayslipPdfLogo>>,
  marginLeft: number,
  marginRight: number,
): number {
  const pageWidth = doc.internal.pageSize.getWidth();
  const logoGap = 3;
  const logoMaxWidth = 30;
  const logoHeight = 7.5;
  let textLeft = marginLeft;
  let textBaseline = 10;

  if (logo && logo.width > 0 && logo.height > 0) {
    const logoWidth = Math.min(
      logoMaxWidth,
      (logo.width / logo.height) * logoHeight,
    );
    const renderedLogoHeight = logoWidth / (logo.width / logo.height);
    doc.addImage(
      logo.dataUrl,
      logo.format,
      marginLeft,
      7.5,
      logoWidth,
      renderedLogoHeight,
      undefined,
      "FAST",
    );
    textLeft = marginLeft + logoWidth + logoGap;
  }

  doc.setFont("times", "bold");
  doc.setFontSize(13);
  doc.setTextColor(...BRAND_DARK);
  doc.text(pdfSafeText(options.venueName), textLeft, textBaseline);
  textBaseline += 4.5;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(9.5);
  doc.setTextColor(...BRAND_DARK);
  doc.text("Attendance Insights", textLeft, textBaseline);
  textBaseline += 4;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(72, 78, 42);
  doc.text(pdfSafeText(options.periodLabel), textLeft, textBaseline);

  const ruleY = Math.max(
    logo ? 7.5 + logoHeight + 1.5 : 0,
    textBaseline + 2.5,
  );
  doc.setDrawColor(...RULE_COLOR);
  doc.setLineWidth(0.4);
  doc.line(marginLeft, ruleY, pageWidth - marginRight, ruleY);

  return Math.max(22, ruleY + 3);
}

function drawPageFooter(
  doc: jsPDF,
  exportedAt: Date,
  userDisplayName: string,
  page: number,
  pageCount: number,
  marginLeft: number,
  marginRight: number,
) {
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const footerY = pageHeight - 8;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(7);
  doc.setTextColor(...FOOTER_TEXT);
  doc.text(
    pdfSafeText(buildInternalDocumentLine(exportedAt, userDisplayName)),
    marginLeft,
    footerY,
  );
  doc.text(
    `Page ${page} of ${pageCount}`,
    pageWidth - marginRight,
    footerY,
    { align: "right" },
  );
}

function lastTableY(doc: jsPDF, fallback: number): number {
  const last = (doc as jsPDF & { lastAutoTable?: { finalY?: number } })
    .lastAutoTable;
  return last?.finalY ?? fallback;
}

/** Generate and download the current Insights table view as PDF. */
export async function exportAttendanceInsightsPdf(
  options: ExportAttendanceInsightsPdfOptions,
): Promise<void> {
  if (options.groups.length === 0) {
    throw new Error("No staff match the selected period.");
  }

  const doc = new jsPDF({
    orientation: "landscape",
    unit: "mm",
    format: "a4",
  });
  const marginLeft = 10;
  const marginRight = 10;
  const logo = options.venueLogoUrl
    ? await loadPayslipPdfLogo(options.venueLogoUrl)
    : null;

  let y = drawPageHeader(
    doc,
    {
      venueName: options.venueName,
      periodLabel: options.periodLabel,
    },
    logo,
    marginLeft,
    marginRight,
  );

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(...BRAND_DARK);
  doc.text(pdfSafeText(options.summaryLine), marginLeft, y);
  y += 4;
  doc.setFontSize(7.5);
  doc.setTextColor(80, 80, 80);
  doc.text(
    "Complete punches / roster SHIFT days. Leave, day off, and absence days are excluded.",
    marginLeft,
    y,
  );
  y += 5;

  const tableMargin = {
    left: marginLeft,
    right: marginRight,
    top: 12,
    bottom: 14,
  };

  if (options.departmentScores.length > 0) {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    doc.setTextColor(...BRAND_DARK);
    doc.text("By department", marginLeft, y);
    y += 4;

    autoTable(doc, {
      startY: y,
      margin: tableMargin,
      head: [["Department", "Staff", "Shift days", "Complete", "Punch complete"]],
      body: options.departmentScores.map((row) => [
        pdfSafeText(row.departmentName),
        String(row.staffCount),
        String(row.dayCount),
        String(row.completeDayCount),
        formatPct(row.punchCompletePct),
      ]),
      theme: "grid",
      styles: {
        font: "helvetica",
        fontSize: 7.5,
        cellPadding: 1.3,
        textColor: BRAND_DARK,
        lineColor: [200, 200, 190],
        lineWidth: 0.15,
        valign: "middle",
      },
      headStyles: {
        fillColor: HEADER_BG,
        textColor: BRAND_DARK,
        fontStyle: "bold",
        fontSize: 7,
      },
      columnStyles: {
        0: { cellWidth: "auto" },
        1: { cellWidth: 22, halign: "right" },
        2: { cellWidth: 28, halign: "right" },
        3: { cellWidth: 28, halign: "right" },
        4: { cellWidth: 32, halign: "right" },
      },
      didParseCell(data) {
        if (data.section !== "body" || data.column.index !== 4) return;
        const score = options.departmentScores[data.row.index];
        if (!score) return;
        data.cell.styles.textColor = punchPctColor(score.punchCompletePct);
        data.cell.styles.fontStyle = "bold";
      },
    });
    y = lastTableY(doc, y) + 8;
  }

  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(...BRAND_DARK);
  doc.text("Staff by department", marginLeft, y);
  y += 4;

  const staffHead = [
    "Emp no",
    "Staff",
    "Employment",
    "Working",
    "Shift days",
    "Hours worked",
    "Punch complete",
  ];

  const body: Array<
    | string[]
    | Array<{
        content: string;
        colSpan?: number;
        styles?: {
          fillColor?: [number, number, number];
          textColor?: [number, number, number];
          fontStyle?: "bold" | "normal";
          halign?: "left" | "right" | "center";
          fontSize?: number;
        };
      }>
  > = [];
  const punchColors: Array<number | null> = [];

  let totalHours = 0;
  let totalDays = 0;
  let totalComplete = 0;
  let staffCount = 0;

  for (const group of options.groups) {
    staffCount += group.rows.length;
    totalHours += group.totalHours;
    totalDays += group.dayCount;
    totalComplete += group.completeDayCount;
    body.push([
      {
        content: pdfSafeText(
          `${group.departmentName}   (${group.rows.length} staff · ${formatHours(group.totalHours)} hrs · ${formatPct(group.punchCompletePct)})`,
        ),
        colSpan: 7,
        styles: {
          fillColor: DEPT_BAND_BG,
          textColor: BRAND_DARK,
          fontStyle: "bold",
          fontSize: 8,
          halign: "left",
        },
      },
    ]);
    punchColors.push(null);
    for (const row of group.rows) {
      body.push([
        pdfSafeText(row.empNo || "-"),
        pdfSafeText(row.fullName || "-"),
        pdfSafeText(row.employmentStatus?.trim() || "-"),
        pdfSafeText(row.workingStatus?.trim() || "-"),
        shiftDaysLabel(row.completeDayCount, row.dayCount),
        formatHours(row.totalHours),
        row.punchCompletePct == null ? "-" : formatPct(row.punchCompletePct),
      ]);
      punchColors.push(row.punchCompletePct);
    }
  }

  autoTable(doc, {
    startY: y,
    margin: tableMargin,
    head: [staffHead.map(pdfSafeText)],
    body,
    foot: [
      [
        {
          content: pdfSafeText(`Total  |  ${staffCount} staff`),
          colSpan: 4,
          styles: { halign: "left", fontStyle: "bold" },
        },
        {
          content: shiftDaysLabel(totalComplete, totalDays),
          styles: { halign: "right", fontStyle: "bold" },
        },
        {
          content: formatHours(totalHours),
          styles: { halign: "right", fontStyle: "bold" },
        },
        {
          content:
            totalDays === 0
              ? "-"
              : formatPct((totalComplete / totalDays) * 100),
          styles: { halign: "right", fontStyle: "bold" },
        },
      ],
    ],
    theme: "grid",
    styles: {
      font: "helvetica",
      fontSize: 7.5,
      cellPadding: 1.3,
      textColor: BRAND_DARK,
      lineColor: [200, 200, 190],
      lineWidth: 0.15,
      overflow: "linebreak",
      valign: "middle",
    },
    headStyles: {
      fillColor: HEADER_BG,
      textColor: BRAND_DARK,
      fontStyle: "bold",
      fontSize: 7,
    },
    footStyles: {
      fillColor: TOTALS_BG,
      textColor: BRAND_DARK,
      fontStyle: "bold",
      fontSize: 7.5,
    },
    columnStyles: {
      0: { cellWidth: 22 },
      1: { cellWidth: "auto" },
      2: { cellWidth: 32 },
      3: { cellWidth: 32 },
      4: { cellWidth: 24, halign: "right" },
      5: { cellWidth: 28, halign: "right" },
      6: { cellWidth: 28, halign: "right" },
    },
    didParseCell(data) {
      if (data.section !== "body" || data.column.index !== 6) return;
      const pct = punchColors[data.row.index];
      if (pct == null) return;
      data.cell.styles.textColor = punchPctColor(pct);
      data.cell.styles.fontStyle = "bold";
    },
  });

  const pageCount = doc.getNumberOfPages();
  for (let page = 1; page <= pageCount; page += 1) {
    doc.setPage(page);
    drawPageFooter(
      doc,
      options.exportedAt,
      options.userDisplayName,
      page,
      pageCount,
      marginLeft,
      marginRight,
    );
  }

  doc.save(
    buildAttendanceInsightsPdfFilename({
      venueName: options.venueName,
      fromDate: options.fromDate,
      toDate: options.toDate,
      exportedAt: options.exportedAt,
    }),
  );
}
