"use client";

import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import { floorPayoutToAed5, formatBenefitMonthLabel } from "@/lib/hr/benefits";
import { loadPayslipPdfLogo } from "@/lib/hr/payslip-pdf";

export type BenefitRunExportKind = "gratuity" | "service_charge";

export type BenefitRunExportRow = {
  empNo: string;
  fullName: string;
  position: string;
  department: string;
  points: number | null;
  workedDays: number | null;
  deductionPercent: number;
  retain: number;
};

export type BenefitRunExportSummaryCard = {
  label: string;
  value: string;
};

export type ExportBenefitRunPdfOptions = {
  kind: BenefitRunExportKind;
  venueName: string;
  venueLogoUrl?: string | null;
  benefitMonth: string;
  periodStart: string;
  periodEnd: string;
  distributionDate?: string | null;
  statusLabel: string;
  payoutMode: "rounded" | "exact";
  rows: BenefitRunExportRow[];
  summaryCards: BenefitRunExportSummaryCard[];
  exportedAt: Date;
  userDisplayName: string;
};

const BRAND_DARK: [number, number, number] = [61, 66, 31];
const HEADER_BG: [number, number, number] = [240, 243, 221];
const DEPT_BAND_BG: [number, number, number] = [226, 232, 200];
const TOTALS_BG: [number, number, number] = [248, 249, 244];
const FOOTER_TEXT: [number, number, number] = [110, 110, 110];

function pdfSafeText(value: string): string {
  return value
    .replace(/[\u2013\u2014\u2212]/g, "-")
    .replace(/[\u00B7\u2022]/g, "|")
    .replace(/[^\x20-\x7E]/g, "?");
}

function moneyPlain(amount: number): string {
  return new Intl.NumberFormat("en-AE", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  }).format(amount);
}

function round2(n: number): number {
  return Math.round((n + Number.EPSILON) * 100) / 100;
}

function payoutOf(amount: number, mode: "rounded" | "exact"): number {
  return mode === "rounded" ? floorPayoutToAed5(amount) : round2(amount);
}

function formatExportTimestamp(date: Date): string {
  return date.toLocaleString("en-GB", {
    day: "2-digit",
    month: "short",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
}

function buildInternalDocumentLine(
  exportedAt: Date,
  userDisplayName: string,
): string {
  const name = userDisplayName.trim() || "Unknown";
  return `File created on: ${formatExportTimestamp(exportedAt)} - Generated by ${name}  |  Internal document`;
}

function kindTitle(kind: BenefitRunExportKind): string {
  return kind === "gratuity" ? "Gratuity run" : "Service charge run";
}

function payoutHeader(mode: "rounded" | "exact"): string {
  return mode === "rounded" ? "Indv Rounded" : "Indv Exact";
}

function slugPart(value: string): string {
  return value
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 40);
}

function buildFilename(
  venueName: string,
  kind: BenefitRunExportKind,
  benefitMonth: string,
  exportedAt: Date,
): string {
  const stamp = exportedAt.toISOString().slice(0, 10);
  return `${slugPart(venueName) || "venue"}-${kind}-${String(benefitMonth).slice(0, 7)}-${stamp}.pdf`;
}

function groupRowsByDepartment(
  rows: BenefitRunExportRow[],
): { department: string; rows: BenefitRunExportRow[] }[] {
  const map = new Map<string, BenefitRunExportRow[]>();
  for (const row of rows) {
    const key = row.department.trim() || "Unassigned";
    const list = map.get(key);
    if (list) list.push(row);
    else map.set(key, [row]);
  }
  return [...map.entries()]
    .sort(([a], [b]) => a.localeCompare(b, undefined, { sensitivity: "base" }))
    .map(([department, groupRows]) => ({ department, rows: groupRows }));
}

function drawFooter(
  doc: jsPDF,
  exportedAt: Date,
  userDisplayName: string,
  marginLeft: number,
  marginRight: number,
): void {
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageCount = doc.getNumberOfPages();
  for (let page = 1; page <= pageCount; page += 1) {
    doc.setPage(page);
    doc.setFontSize(7.5);
    doc.setTextColor(...FOOTER_TEXT);
    doc.text(
      pdfSafeText(buildInternalDocumentLine(exportedAt, userDisplayName)),
      marginLeft,
      doc.internal.pageSize.getHeight() - 8,
    );
    doc.text(
      `Page ${page} of ${pageCount}`,
      pageWidth - marginRight,
      doc.internal.pageSize.getHeight() - 8,
      { align: "right" },
    );
  }
}

export async function exportBenefitRunPdf(
  options: ExportBenefitRunPdfOptions,
): Promise<void> {
  const {
    kind,
    venueName,
    venueLogoUrl,
    benefitMonth,
    periodStart,
    periodEnd,
    distributionDate,
    statusLabel,
    payoutMode,
    rows,
    summaryCards,
    exportedAt,
    userDisplayName,
  } = options;

  const doc = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" });
  const marginLeft = 12;
  const marginRight = 12;
  const pageWidth = doc.internal.pageSize.getWidth();
  const logo = venueLogoUrl ? await loadPayslipPdfLogo(venueLogoUrl) : null;

  let y = 12;
  if (logo && logo.width > 0 && logo.height > 0) {
    const logoHeight = 8;
    const logoWidth = Math.min(32, (logo.width / logo.height) * logoHeight);
    doc.addImage(
      logo.dataUrl,
      logo.format,
      marginLeft,
      y - 2,
      logoWidth,
      logoWidth / (logo.width / logo.height),
    );
  }

  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(...BRAND_DARK);
  doc.text(pdfSafeText(venueName), pageWidth - marginRight, y, {
    align: "right",
  });
  y += 6;
  doc.setFontSize(12);
  doc.text(kindTitle(kind), pageWidth - marginRight, y, { align: "right" });
  y += 5;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(80, 80, 80);
  const periodLine = [
    formatBenefitMonthLabel(benefitMonth),
    `${periodStart.slice(0, 10)} -> ${periodEnd.slice(0, 10)}`,
    distributionDate ? `Distribute ${distributionDate.slice(0, 10)}` : null,
    statusLabel,
  ]
    .filter(Boolean)
    .join("  |  ");
  doc.text(pdfSafeText(periodLine), pageWidth - marginRight, y, {
    align: "right",
  });
  y += 7;

  if (summaryCards.length > 0) {
    const summaryText = summaryCards
      .map((card) => `${card.label}: ${card.value}`)
      .join("   ");
    doc.setFontSize(8);
    doc.setTextColor(...BRAND_DARK);
    doc.text(pdfSafeText(summaryText), marginLeft, y);
    y += 5;
  }

  const head = [
    "Emp no",
    "Name",
    "Position",
    "Points",
    "Days",
    "Deduction",
    "Retain",
    payoutHeader(payoutMode),
  ];

  const groups = groupRowsByDepartment(rows);
  let cursorY = y;
  let totalRetain = 0;
  let totalPayout = 0;

  if (groups.length === 0) {
    autoTable(doc, {
      startY: cursorY,
      head: [head.map(pdfSafeText)],
      body: [["-", "No allocations", "-", "-", "-", "-", "-", "-"].map(pdfSafeText)],
      theme: "grid",
      styles: {
        fontSize: 7.5,
        cellPadding: 1.3,
        textColor: BRAND_DARK,
        lineColor: [200, 200, 190],
        lineWidth: 0.15,
      },
      headStyles: {
        fillColor: HEADER_BG,
        textColor: BRAND_DARK,
        fontStyle: "bold",
        fontSize: 7,
      },
      margin: { left: marginLeft, right: marginRight, bottom: 14 },
    });
  }

  for (const group of groups) {
    let groupRetain = 0;
    let groupPayout = 0;
    const body = group.rows.map((row) => {
      const payout = payoutOf(row.retain, payoutMode);
      groupRetain += row.retain;
      groupPayout += payout;
      totalRetain += row.retain;
      totalPayout += payout;
      return [
        row.empNo || "-",
        row.fullName || "-",
        row.position || "-",
        row.points == null ? "-" : String(row.points),
        row.workedDays == null ? "-" : String(row.workedDays),
        row.deductionPercent > 0 ? `${row.deductionPercent}%` : "-",
        moneyPlain(row.retain),
        moneyPlain(payout),
      ].map(pdfSafeText);
    });

    autoTable(doc, {
      startY: cursorY,
      head: [
        [
          {
            content: pdfSafeText(
              `${group.department}  (${group.rows.length})`,
            ),
            colSpan: 8,
            styles: {
              fillColor: DEPT_BAND_BG,
              textColor: BRAND_DARK,
              fontStyle: "bold",
              fontSize: 8,
              halign: "left",
            },
          },
        ],
        head.map(pdfSafeText),
      ],
      body,
      foot: [
        [
          "Subtotal",
          "",
          "",
          "",
          "",
          "",
          moneyPlain(round2(groupRetain)),
          moneyPlain(round2(groupPayout)),
        ].map(pdfSafeText),
      ],
      theme: "grid",
      styles: {
        fontSize: 7.5,
        cellPadding: 1.3,
        textColor: BRAND_DARK,
        lineColor: [200, 200, 190],
        lineWidth: 0.15,
        overflow: "linebreak",
        valign: "middle",
      },
      headStyles: {
        fillColor: HEADER_BG,
        textColor: BRAND_DARK,
        fontStyle: "bold",
        fontSize: 7,
      },
      footStyles: {
        fillColor: TOTALS_BG,
        textColor: BRAND_DARK,
        fontStyle: "bold",
        fontSize: 7.5,
      },
      columnStyles: {
        0: { cellWidth: 20 },
        1: { cellWidth: 52 },
        2: { cellWidth: 44 },
        3: { halign: "center", cellWidth: 18 },
        4: { halign: "center", cellWidth: 16 },
        5: { halign: "right", cellWidth: 22 },
        6: { halign: "right", cellWidth: 28 },
        7: { halign: "right", cellWidth: 28 },
      },
      margin: { left: marginLeft, right: marginRight, bottom: 14 },
    });

    const last = (doc as jsPDF & { lastAutoTable?: { finalY?: number } })
      .lastAutoTable;
    cursorY = (last?.finalY ?? cursorY) + 4;
  }

  if (groups.length > 0) {
    autoTable(doc, {
      startY: cursorY,
      body: [
        [
          {
            content: pdfSafeText(`Total  |  ${rows.length} staff`),
            colSpan: 6,
            styles: { halign: "left", fontStyle: "bold" },
          },
          {
            content: pdfSafeText(moneyPlain(round2(totalRetain))),
            styles: { halign: "right", fontStyle: "bold" },
          },
          {
            content: pdfSafeText(moneyPlain(round2(totalPayout))),
            styles: { halign: "right", fontStyle: "bold" },
          },
        ],
      ],
      theme: "grid",
      styles: {
        fontSize: 8,
        cellPadding: 1.5,
        textColor: BRAND_DARK,
        fillColor: TOTALS_BG,
        lineColor: [200, 200, 190],
        lineWidth: 0.15,
      },
      columnStyles: {
        0: { cellWidth: 20 },
        1: { cellWidth: 52 },
        2: { cellWidth: 44 },
        3: { cellWidth: 18 },
        4: { cellWidth: 16 },
        5: { cellWidth: 22 },
        6: { cellWidth: 28 },
        7: { cellWidth: 28 },
      },
      margin: { left: marginLeft, right: marginRight, bottom: 14 },
    });
  }

  drawFooter(doc, exportedAt, userDisplayName, marginLeft, marginRight);
  doc.save(buildFilename(venueName, kind, benefitMonth, exportedAt));
}
