"use client";

import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import { loadPayslipPdfLogo } from "@/lib/hr/payslip-pdf";
import {
  buildExcelWorkbook,
  downloadExcelWorkbook,
} from "@/lib/sales/excel-utils";
import type { CertificationExpenseMonth } from "@/lib/hr/types";

export type CertificationExpensesExportFormat = "pdf" | "excel";

export type ExportCertificationExpensesOptions = {
  venueName: string;
  venueLogoUrl?: string | null;
  month: CertificationExpenseMonth;
  exportedAt: Date;
  userDisplayName: string;
};

const BRAND_DARK: [number, number, number] = [61, 66, 31];
const HEADER_BG: [number, number, number] = [240, 243, 221];
const TOTALS_BG: [number, number, number] = [226, 232, 200];
const FOOTER_TEXT: [number, number, number] = [110, 110, 110];

const TABLE_HEADERS = [
  "Certification",
  "Qty",
  "Net",
  "VAT",
  "Gross",
] as const;

function sanitizeFilenamePart(value: string): string {
  return value
    .trim()
    .replace(/[\\/:*?"<>|]/g, "")
    .replace(/\s+/g, " ");
}

function formatExportDateStamp(date: Date): string {
  const day = String(date.getDate()).padStart(2, "0");
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const year = String(date.getFullYear()).slice(-2);
  return `${day}-${month}-${year}`;
}

function formatExportTimestamp(date: Date): string {
  const day = String(date.getDate()).padStart(2, "0");
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const year = date.getFullYear();
  const hours = String(date.getHours()).padStart(2, "0");
  const minutes = String(date.getMinutes()).padStart(2, "0");
  return `${day}/${month}/${year} ${hours}:${minutes}`;
}

function buildInternalDocumentLine(
  exportedAt: Date,
  userDisplayName: string,
): string {
  const name = userDisplayName.trim() || "Unknown";
  return `File created on: ${formatExportTimestamp(exportedAt)} — Generated by ${name}   |   Internal document`;
}

function pdfSafeText(value: string): string {
  return value.replace(/[^\x20-\x7E]/g, "?");
}

function certLabel(line: CertificationExpenseMonth["lines"][number]): string {
  if (
    line.label &&
    line.label.toLowerCase() !== line.name.toLowerCase()
  ) {
    return `${line.label} · ${line.name}`;
  }
  return line.name;
}

function moneyPlain(amount: number): string {
  return new Intl.NumberFormat("en-AE", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  }).format(amount);
}

export function buildCertificationExpensesFilename(
  venueName: string,
  monthLabel: string,
  format: CertificationExpensesExportFormat,
  exportedAt: Date = new Date(),
): string {
  const venue = sanitizeFilenamePart(venueName);
  const month = sanitizeFilenamePart(monthLabel);
  const stamp = formatExportDateStamp(exportedAt);
  const extension = format === "pdf" ? "pdf" : "xlsx";
  return `${venue} Certification Expenses ${month} ${stamp}.${extension}`;
}

function buildBodyRows(month: CertificationExpenseMonth): string[][] {
  return month.lines.map((line) => [
    certLabel(line),
    String(line.count),
    moneyPlain(line.net),
    moneyPlain(line.vat),
    moneyPlain(line.gross),
  ]);
}

async function exportCertificationExpensesPdf(
  options: ExportCertificationExpensesOptions,
): Promise<void> {
  const { venueName, venueLogoUrl, month, exportedAt, userDisplayName } =
    options;
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const marginLeft = 14;
  const marginRight = 14;
  const pageWidth = doc.internal.pageSize.getWidth();
  const logo = venueLogoUrl ? await loadPayslipPdfLogo(venueLogoUrl) : null;

  let y = 12;
  if (logo && logo.width > 0 && logo.height > 0) {
    const logoHeight = 8;
    const logoWidth = Math.min(
      32,
      (logo.width / logo.height) * logoHeight,
    );
    doc.addImage(
      logo.dataUrl,
      logo.format,
      marginLeft,
      y - 2,
      logoWidth,
      logoWidth / (logo.width / logo.height),
    );
  }

  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(...BRAND_DARK);
  doc.text(pdfSafeText(venueName), pageWidth - marginRight, y, {
    align: "right",
  });
  y += 6;
  doc.setFontSize(12);
  doc.text("Certification expenses", pageWidth - marginRight, y, {
    align: "right",
  });
  y += 5;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(80, 80, 80);
  doc.text(pdfSafeText(month.label), pageWidth - marginRight, y, {
    align: "right",
  });
  y += 8;

  const body = buildBodyRows(month);
  autoTable(doc, {
    startY: y,
    head: [Array.from(TABLE_HEADERS)],
    body,
    foot: [
      [
        "Month total",
        String(month.totalCount),
        moneyPlain(month.totalNet),
        moneyPlain(month.totalVat),
        moneyPlain(month.totalGross),
      ],
    ],
    theme: "grid",
    styles: {
      fontSize: 9,
      cellPadding: 2.2,
      textColor: BRAND_DARK,
      lineColor: [200, 200, 190],
      lineWidth: 0.2,
    },
    headStyles: {
      fillColor: HEADER_BG,
      textColor: BRAND_DARK,
      fontStyle: "bold",
    },
    footStyles: {
      fillColor: TOTALS_BG,
      textColor: BRAND_DARK,
      fontStyle: "bold",
    },
    columnStyles: {
      0: { cellWidth: "auto" },
      1: { halign: "right", cellWidth: 18 },
      2: { halign: "right", cellWidth: 28 },
      3: { halign: "right", cellWidth: 28 },
      4: { halign: "right", cellWidth: 28 },
    },
    margin: { left: marginLeft, right: marginRight },
  });

  const pageCount = doc.getNumberOfPages();
  for (let page = 1; page <= pageCount; page += 1) {
    doc.setPage(page);
    doc.setFontSize(7.5);
    doc.setTextColor(...FOOTER_TEXT);
    doc.text(
      pdfSafeText(buildInternalDocumentLine(exportedAt, userDisplayName)),
      marginLeft,
      doc.internal.pageSize.getHeight() - 8,
    );
    doc.text(
      `Page ${page} of ${pageCount}`,
      pageWidth - marginRight,
      doc.internal.pageSize.getHeight() - 8,
      { align: "right" },
    );
  }

  doc.save(
    buildCertificationExpensesFilename(
      venueName,
      month.label,
      "pdf",
      exportedAt,
    ),
  );
}

async function exportCertificationExpensesExcel(
  options: ExportCertificationExpensesOptions,
): Promise<void> {
  const { venueName, month, exportedAt, userDisplayName } = options;
  const dataRows = month.lines.map((line) => [
    certLabel(line),
    line.count,
    Number(line.net.toFixed(2)),
    Number(line.vat.toFixed(2)),
    Number(line.gross.toFixed(2)),
  ]);
  dataRows.push([
    "Month total",
    month.totalCount,
    Number(month.totalNet.toFixed(2)),
    Number(month.totalVat.toFixed(2)),
    Number(month.totalGross.toFixed(2)),
  ]);

  const workbook = await buildExcelWorkbook(
    "Expenses",
    Array.from(TABLE_HEADERS),
    dataRows,
    [
      ["Certification expenses"],
      ["Venue", venueName],
      ["Month", month.label],
      ["Generated", formatExportTimestamp(exportedAt)],
      ["Generated by", userDisplayName],
      [],
      ["Amounts are AED. Costs follow certificate issue dates."],
      [
        "Employee-provided certificates are excluded from company expenses.",
      ],
    ],
  );

  const staffRows: (string | number)[][] = [];
  for (const line of month.lines) {
    for (const person of line.staff) {
        staffRows.push([
        certLabel(line),
        person.empNo,
        person.fullName,
        person.certifiedAt,
        line.count > 0 ? Number((line.net / line.count).toFixed(2)) : 0,
        line.count > 0 ? Number((line.vat / line.count).toFixed(2)) : 0,
        line.count > 0 ? Number((line.gross / line.count).toFixed(2)) : 0,
      ]);
    }
  }

  if (staffRows.length > 0) {
    const XLSX = await import("xlsx");
    const sheet = XLSX.utils.aoa_to_sheet([
      [
        "Certification",
        "Emp no",
        "Employee",
        "Issue date",
        "Net",
        "VAT",
        "Gross",
      ],
      ...staffRows,
    ]);
    XLSX.utils.book_append_sheet(workbook, sheet, "Employees");
  }

  await downloadExcelWorkbook(
    workbook,
    buildCertificationExpensesFilename(
      venueName,
      month.label,
      "excel",
      exportedAt,
    ),
  );
}

export async function exportCertificationExpenses(
  format: CertificationExpensesExportFormat,
  options: ExportCertificationExpensesOptions,
): Promise<void> {
  if (format === "pdf") {
    await exportCertificationExpensesPdf(options);
    return;
  }
  await exportCertificationExpensesExcel(options);
}

/** Prefer current month when present, else newest available. */
export function defaultCertificationExpenseMonthKey(
  months: CertificationExpenseMonth[],
): string {
  if (months.length === 0) return "";
  const now = new Date();
  const currentKey = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}`;
  if (months.some((m) => m.monthKey === currentKey)) return currentKey;
  return [...months].sort((a, b) =>
    a.monthKey < b.monthKey ? 1 : a.monthKey > b.monthKey ? -1 : 0,
  )[0]?.monthKey ?? "";
}
