/** Map nationality / country display names → ISO 3166-1 alpha-2 for flag emoji. */
const NATIONALITY_ISO: Record<string, string> = {
  afghanistan: "AF",
  albania: "AL",
  algeria: "DZ",
  argentina: "AR",
  armenia: "AM",
  australia: "AU",
  austria: "AT",
  azerbaijan: "AZ",
  bangladesh: "BD",
  belarus: "BY",
  belgium: "BE",
  brazil: "BR",
  bulgaria: "BG",
  cambodia: "KH",
  cameroon: "CM",
  canada: "CA",
  chile: "CL",
  china: "CN",
  colombia: "CO",
  croatia: "HR",
  "czech republic": "CZ",
  czechia: "CZ",
  denmark: "DK",
  egypt: "EG",
  estonia: "EE",
  ethiopia: "ET",
  finland: "FI",
  france: "FR",
  georgia: "GE",
  germany: "DE",
  ghana: "GH",
  greece: "GR",
  hungary: "HU",
  india: "IN",
  indonesia: "ID",
  iran: "IR",
  iraq: "IQ",
  ireland: "IE",
  italy: "IT",
  japan: "JP",
  jordan: "JO",
  kazakhstan: "KZ",
  kenya: "KE",
  korea: "KR",
  "south korea": "KR",
  "north korea": "KP",
  kuwait: "KW",
  kyrgyzstan: "KG",
  latvia: "LV",
  lebanon: "LB",
  lithuania: "LT",
  malaysia: "MY",
  mexico: "MX",
  morocco: "MA",
  myanmar: "MM",
  burma: "MM",
  nepal: "NP",
  netherlands: "NL",
  "new zealand": "NZ",
  nigeria: "NG",
  norway: "NO",
  pakistan: "PK",
  palestine: "PS",
  peru: "PE",
  philippines: "PH",
  poland: "PL",
  portugal: "PT",
  romania: "RO",
  russia: "RU",
  "saudi arabia": "SA",
  serbia: "RS",
  singapore: "SG",
  slovakia: "SK",
  "south africa": "ZA",
  spain: "ES",
  "sri lanka": "LK",
  sudan: "SD",
  sweden: "SE",
  switzerland: "CH",
  syria: "SY",
  taiwan: "TW",
  tanzania: "TZ",
  thailand: "TH",
  tunisia: "TN",
  turkey: "TR",
  uganda: "UG",
  ukraine: "UA",
  "united arab emirates": "AE",
  uae: "AE",
  "united kingdom": "GB",
  uk: "GB",
  "united states": "US",
  usa: "US",
  uzbekistan: "UZ",
  venezuela: "VE",
  vietnam: "VN",
  yemen: "YE",
  zimbabwe: "ZW",
  bahrain: "BH",
  oman: "OM",
  qatar: "QA",
  "dominican republic": "DO",
  "ivory coast": "CI",
  "cote d'ivoire": "CI",
  "hong kong": "HK",
  macau: "MO",
  macao: "MO",
};

/** UN M49-style continent for ISO 3166-1 alpha-2 codes we map. */
const ISO_CONTINENT: Record<string, string> = {
  AF: "Asia",
  AL: "Europe",
  DZ: "Africa",
  AR: "South America",
  AM: "Asia",
  AU: "Oceania",
  AT: "Europe",
  AZ: "Asia",
  BD: "Asia",
  BY: "Europe",
  BE: "Europe",
  BR: "South America",
  BG: "Europe",
  BH: "Asia",
  KH: "Asia",
  CM: "Africa",
  CA: "North America",
  CL: "South America",
  CN: "Asia",
  CO: "South America",
  CI: "Africa",
  HR: "Europe",
  CZ: "Europe",
  DK: "Europe",
  DO: "North America",
  EG: "Africa",
  EE: "Europe",
  ET: "Africa",
  FI: "Europe",
  FR: "Europe",
  GE: "Asia",
  DE: "Europe",
  GH: "Africa",
  GR: "Europe",
  HK: "Asia",
  HU: "Europe",
  IN: "Asia",
  ID: "Asia",
  IR: "Asia",
  IQ: "Asia",
  IE: "Europe",
  IT: "Europe",
  JP: "Asia",
  JO: "Asia",
  KZ: "Asia",
  KE: "Africa",
  KR: "Asia",
  KP: "Asia",
  KW: "Asia",
  KG: "Asia",
  LV: "Europe",
  LB: "Asia",
  LT: "Europe",
  MY: "Asia",
  MX: "North America",
  MM: "Asia",
  MA: "Africa",
  MO: "Asia",
  NP: "Asia",
  NL: "Europe",
  NZ: "Oceania",
  NG: "Africa",
  NO: "Europe",
  OM: "Asia",
  PK: "Asia",
  PS: "Asia",
  PE: "South America",
  PH: "Asia",
  PL: "Europe",
  PT: "Europe",
  QA: "Asia",
  RO: "Europe",
  RU: "Europe",
  SA: "Asia",
  RS: "Europe",
  SG: "Asia",
  SK: "Europe",
  ZA: "Africa",
  ES: "Europe",
  LK: "Asia",
  SD: "Africa",
  SE: "Europe",
  CH: "Europe",
  SY: "Asia",
  TW: "Asia",
  TZ: "Africa",
  TH: "Asia",
  TN: "Africa",
  TR: "Asia",
  UG: "Africa",
  UA: "Europe",
  AE: "Asia",
  GB: "Europe",
  US: "North America",
  UZ: "Asia",
  VE: "South America",
  VN: "Asia",
  YE: "Asia",
  ZW: "Africa",
};

export function continentFromNationalityName(
  name: string | null | undefined,
): string | null {
  const iso = isoFromNationalityName(name);
  if (!iso) return null;
  return ISO_CONTINENT[iso] ?? null;
}

export function isoFromNationalityName(
  name: string | null | undefined,
): string | null {
  const key = name?.trim().toLowerCase();
  if (!key) return null;
  return NATIONALITY_ISO[key] ?? null;
}

/** Regional-indicator flag emoji for an ISO alpha-2 code (e.g. AE → 🇦🇪). */
export function flagEmojiFromIso(iso2: string | null | undefined): string {
  const code = iso2?.trim().toUpperCase();
  if (!code || !/^[A-Z]{2}$/.test(code)) return "";
  return String.fromCodePoint(
    ...[...code].map((ch) => 0x1f1e6 - 65 + ch.charCodeAt(0)),
  );
}

export function nationalityDisplay(
  name: string | null | undefined,
): { flag: string; label: string } | null {
  const label = name?.trim() || "";
  if (!label) return null;
  const iso = isoFromNationalityName(label);
  return {
    flag: flagEmojiFromIso(iso),
    label,
  };
}
