"use client";

import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import {
  SCHEDULE_DEPARTMENTS,
  formatShiftRangeLabel,
  formatWeekRangeLabel,
  getMondayForWeekOffset,
  getScheduleDayLabel,
  getShiftTemplate,
  getWeekDayColumns,
  scheduleCellKey,
  type ScheduleCellValue,
  type ScheduleDayLabel,
  type ScheduleDepartmentKey,
  type ScheduleStaffRow,
  type ScheduleWeekSection,
  type ShiftTemplate,
  type WeekDayColumn,
} from "@/lib/hr/schedules";

export type SchedulesPublishView = "roster" | "sections";

export type SchedulesPublishDepartments = Record<ScheduleDepartmentKey, boolean>;

type PdfLogoAsset = {
  dataUrl: string;
  format: "PNG" | "JPEG" | "WEBP";
  width: number;
  height: number;
};

export type SchedulesPdfDayRow = {
  staff_id: string;
  work_date: string;
  label_code: string;
  shift_template_id: string | null;
};

export type SchedulesPdfDepartmentBlock = {
  departmentKey: ScheduleDepartmentKey;
  departmentLabel: string;
  staff: ScheduleStaffRow[];
  cells: Record<string, ScheduleCellValue>;
  sections: ScheduleWeekSection[];
};

export type ExportSchedulesPdfOptions = {
  venueName: string;
  venueLogoUrl?: string | null;
  weekOffset: number;
  view: SchedulesPublishView;
  departments: SchedulesPublishDepartments;
  blocks: SchedulesPdfDepartmentBlock[];
  labels: ScheduleDayLabel[];
  shiftTemplates: ShiftTemplate[];
  /** Optional YYYY-MM-DD → name map for purple PH column headers. */
  publicHolidayByDate?: ReadonlyMap<string, string>;
  exportedAt: Date;
  userDisplayName: string;
};

const BRAND_DARK: [number, number, number] = [61, 66, 31];
const HEADER_BG: [number, number, number] = [240, 243, 221];
const PH_HEADER_BG: [number, number, number] = [237, 233, 254];
const PH_HEADER_TEXT: [number, number, number] = [91, 33, 182];
const SECTION_BAND_BG: [number, number, number] = [226, 232, 200];
const DEPT_BAND_BG: [number, number, number] = [61, 66, 31];
const STAFF_META_BG: [number, number, number] = [248, 249, 244];
const EMPTY_CELL_BG: [number, number, number] = [255, 255, 255];
const FOOTER_TEXT: [number, number, number] = [110, 110, 110];
const RULE_COLOR: [number, number, number] = [61, 66, 31];
const DAY_COL_COUNT = 7;
const META_COL_COUNT = 2; // Staff + Position
const PH_BODY_BG: [number, number, number] = [245, 243, 255];

function sanitizeFilenamePart(value: string): string {
  return value
    .trim()
    .replace(/[\\/:*?"<>|]/g, "")
    .replace(/\s+/g, " ");
}

function formatExportDateStamp(date: Date): string {
  const day = String(date.getDate()).padStart(2, "0");
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const year = String(date.getFullYear()).slice(-2);
  return `${day}-${month}-${year}`;
}

function formatExportTimestamp(date: Date): string {
  const day = String(date.getDate()).padStart(2, "0");
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const year = date.getFullYear();
  const hours = String(date.getHours()).padStart(2, "0");
  const minutes = String(date.getMinutes()).padStart(2, "0");
  return `${day}/${month}/${year} ${hours}:${minutes}`;
}

export function buildSchedulesInternalDocumentLine(
  exportedAt: Date,
  userDisplayName: string,
): string {
  const name = userDisplayName.trim() || "Unknown";
  return `File created on: ${formatExportTimestamp(exportedAt)} — Generated by ${name}   |   Internal document`;
}

function selectedDepartmentLabels(
  departments: SchedulesPublishDepartments,
): string[] {
  return SCHEDULE_DEPARTMENTS.filter((dept) => departments[dept.key]).map(
    (dept) => dept.label,
  );
}

export function buildSchedulesPdfFilename(
  venueName: string,
  weekLabel: string,
  view: SchedulesPublishView,
  departments: SchedulesPublishDepartments,
  exportedAt: Date = new Date(),
): string {
  const venue = sanitizeFilenamePart(venueName);
  const week = sanitizeFilenamePart(weekLabel);
  const viewPart = view === "roster" ? "Roster" : "Sections";
  const deptPart = sanitizeFilenamePart(
    selectedDepartmentLabels(departments).join(" "),
  );
  const stamp = formatExportDateStamp(exportedAt);
  return `${venue} Schedule (${viewPart} · ${deptPart}) ${week} ${stamp}.pdf`;
}

function parseHexColor(
  hex: string | null | undefined,
): [number, number, number] | null {
  if (!hex) return null;
  const normalized = hex.trim().replace(/^#/, "");
  if (!/^[0-9a-fA-F]{6}$/.test(normalized)) return null;
  return [
    Number.parseInt(normalized.slice(0, 2), 16),
    Number.parseInt(normalized.slice(2, 4), 16),
    Number.parseInt(normalized.slice(4, 6), 16),
  ];
}

async function loadPdfLogoAsset(url: string): Promise<PdfLogoAsset | null> {
  if (typeof window === "undefined") return null;

  try {
    const response = await fetch(url);
    if (!response.ok) return null;

    const blob = await response.blob();

    if (blob.type.includes("svg") || url.endsWith(".svg")) {
      const svgText = await blob.text();
      const svgBlob = new Blob([svgText], {
        type: "image/svg+xml;charset=utf-8",
      });
      const objectUrl = URL.createObjectURL(svgBlob);

      try {
        return await new Promise<PdfLogoAsset | null>((resolve) => {
          const image = new Image();
          image.onload = () => {
            const canvas = document.createElement("canvas");
            canvas.width = image.naturalWidth || 400;
            canvas.height = image.naturalHeight || 400;
            const context = canvas.getContext("2d");
            URL.revokeObjectURL(objectUrl);

            if (!context) {
              resolve(null);
              return;
            }

            context.drawImage(image, 0, 0, canvas.width, canvas.height);
            resolve({
              dataUrl: canvas.toDataURL("image/png"),
              format: "PNG",
              width: canvas.width,
              height: canvas.height,
            });
          };
          image.onerror = () => {
            URL.revokeObjectURL(objectUrl);
            resolve(null);
          };
          image.src = objectUrl;
        });
      } catch {
        URL.revokeObjectURL(objectUrl);
        return null;
      }
    }

    const dataUrl = await new Promise<string>((resolve, reject) => {
      const reader = new FileReader();
      reader.onload = () => resolve(String(reader.result));
      reader.onerror = () => reject(reader.error);
      reader.readAsDataURL(blob);
    });

    const format = blob.type.includes("jpeg")
      ? "JPEG"
      : blob.type.includes("webp")
        ? "WEBP"
        : "PNG";

    return await new Promise<PdfLogoAsset | null>((resolve) => {
      const image = new Image();
      image.onload = () =>
        resolve({
          dataUrl,
          format,
          width: image.naturalWidth,
          height: image.naturalHeight,
        });
      image.onerror = () => resolve(null);
      image.src = dataUrl;
    });
  } catch {
    return null;
  }
}

function cellPresentation(
  labels: ScheduleDayLabel[],
  shiftTemplates: ShiftTemplate[],
  value: ScheduleCellValue | null,
) {
  if (!value) return null;

  if (value.labelCode === "SHIFT" && value.shiftTemplateId) {
    const template = getShiftTemplate(shiftTemplates, value.shiftTemplateId);
    if (template) {
      return {
        abbreviation: template.abbreviation,
        name: `${template.name} (${formatShiftRangeLabel(template.startTime, template.endTime)})`,
        bgColor: template.bgColor,
        textColor: template.textColor,
      };
    }
  }

  const label = getScheduleDayLabel(labels, value.labelCode);
  if (!label) return null;
  return {
    abbreviation: label.abbreviation,
    name: label.name,
    bgColor: label.bgColor,
    textColor: label.textColor,
  };
}

type TableRowMeta =
  | { kind: "department"; title: string }
  | { kind: "section"; title: string }
  | { kind: "note" }
  | {
      kind: "staff";
      presentationByDay: Array<ReturnType<typeof cellPresentation>>;
    };

type CellValue = string | { content: string; colSpan?: number };

function staffNameCell(member: ScheduleStaffRow): string {
  const status = member.workingStatus?.trim();
  return status ? `${member.fullName} · ${status}` : member.fullName;
}

function buildRosterRows(
  staff: ScheduleStaffRow[],
  days: WeekDayColumn[],
  cells: Record<string, ScheduleCellValue>,
  labels: ScheduleDayLabel[],
  shiftTemplates: ShiftTemplate[],
): { body: CellValue[][]; meta: TableRowMeta[] } {
  const body: CellValue[][] = [];
  const meta: TableRowMeta[] = [];

  for (const member of staff) {
    const presentationByDay = days.map((day) =>
      cellPresentation(
        labels,
        shiftTemplates,
        cells[scheduleCellKey(member.id, day.key)] ?? null,
      ),
    );
    body.push([
      staffNameCell(member),
      member.position ?? "—",
      ...presentationByDay.map((p) => p?.abbreviation ?? "·"),
    ]);
    meta.push({ kind: "staff", presentationByDay });
  }

  return { body, meta };
}

function buildSectionsRows(
  staff: ScheduleStaffRow[],
  sections: ScheduleWeekSection[],
  days: WeekDayColumn[],
  cells: Record<string, ScheduleCellValue>,
  labels: ScheduleDayLabel[],
  shiftTemplates: ShiftTemplate[],
): { body: CellValue[][]; meta: TableRowMeta[] } {
  const body: CellValue[][] = [];
  const meta: TableRowMeta[] = [];
  const staffById = new Map(staff.map((member) => [member.id, member]));
  const assigned = new Set<string>();
  const colSpan = META_COL_COUNT + days.length;

  for (const section of sections) {
    body.push([{ content: section.name.toUpperCase(), colSpan }]);
    meta.push({ kind: "section", title: section.name });

    const sectionStaff = section.staffIds
      .map((id) => staffById.get(id))
      .filter((member): member is ScheduleStaffRow => Boolean(member));

    for (const member of sectionStaff) {
      assigned.add(member.id);
      const presentationByDay = days.map((day) =>
        cellPresentation(
          labels,
          shiftTemplates,
          cells[scheduleCellKey(member.id, day.key)] ?? null,
        ),
      );
      body.push([
        staffNameCell(member),
        member.position ?? "—",
        ...presentationByDay.map((p) => p?.abbreviation ?? "·"),
      ]);
      meta.push({ kind: "staff", presentationByDay });
    }

    if (sectionStaff.length === 0) {
      body.push([{ content: "No staff assigned", colSpan }]);
      meta.push({ kind: "note" });
    }
  }

  const unassigned = staff.filter((member) => !assigned.has(member.id));
  body.push([{ content: "UNASSIGNED", colSpan }]);
  meta.push({ kind: "section", title: "Unassigned" });

  if (unassigned.length === 0) {
    body.push([{ content: "No unassigned staff", colSpan }]);
    meta.push({ kind: "note" });
  } else {
    for (const member of unassigned) {
      const presentationByDay = days.map((day) =>
        cellPresentation(
          labels,
          shiftTemplates,
          cells[scheduleCellKey(member.id, day.key)] ?? null,
        ),
      );
      body.push([
        staffNameCell(member),
        member.position ?? "—",
        ...presentationByDay.map((p) => p?.abbreviation ?? "·"),
      ]);
      meta.push({ kind: "staff", presentationByDay });
    }
  }

  return { body, meta };
}

function buildCombinedBody(
  blocks: SchedulesPdfDepartmentBlock[],
  view: SchedulesPublishView,
  days: WeekDayColumn[],
  labels: ScheduleDayLabel[],
  shiftTemplates: ShiftTemplate[],
): { body: CellValue[][]; meta: TableRowMeta[] } {
  const body: CellValue[][] = [];
  const meta: TableRowMeta[] = [];
  const colSpan = META_COL_COUNT + days.length;

  for (const block of blocks) {
    body.push([
      {
        content: `${block.departmentLabel.toUpperCase()}  ·  ${block.staff.length} staff`,
        colSpan,
      },
    ]);
    meta.push({ kind: "department", title: block.departmentLabel });

    const rows =
      view === "roster"
        ? buildRosterRows(
            block.staff,
            days,
            block.cells,
            labels,
            shiftTemplates,
          )
        : buildSectionsRows(
            block.staff,
            block.sections,
            days,
            block.cells,
            labels,
            shiftTemplates,
          );

    if (rows.body.length === 0) {
      body.push([{ content: "No staff in this department", colSpan }]);
      meta.push({ kind: "note" });
      continue;
    }

    body.push(...rows.body);
    meta.push(...rows.meta);
  }

  return { body, meta };
}

function drawPageHeader(
  doc: jsPDF,
  options: {
    venueName: string;
    weekLabel: string;
    viewLabel: string;
    departmentLabels: string[];
    staffCount: number;
  },
  logo: PdfLogoAsset | null,
  marginLeft: number,
  marginRight: number,
): number {
  const pageWidth = doc.internal.pageSize.getWidth();
  const logoGap = 3;
  const logoMaxWidth = 30;
  const logoHeight = 7.5;
  let logoWidth = 0;
  let textLeft = marginLeft;
  let textBaseline = 10;

  if (logo) {
    logoWidth = Math.min(logoMaxWidth, (logo.width / logo.height) * logoHeight);
    const renderedLogoHeight = logoWidth / (logo.width / logo.height);
    doc.addImage(
      logo.dataUrl,
      logo.format,
      marginLeft,
      7.5,
      logoWidth,
      renderedLogoHeight,
      undefined,
      "FAST",
    );
    textLeft = marginLeft + logoWidth + logoGap;
  }

  doc.setFont("times", "bold");
  doc.setFontSize(13);
  doc.setTextColor(...BRAND_DARK);
  doc.text(options.venueName, textLeft, textBaseline);
  textBaseline += 4.5;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(9.5);
  doc.setTextColor(...BRAND_DARK);
  doc.text(
    `Weekly Schedule · ${options.viewLabel}`,
    textLeft,
    textBaseline,
  );
  textBaseline += 4;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(72, 78, 42);
  doc.text(
    `${options.departmentLabels.join(" · ")}  ·  ${options.weekLabel}  ·  ${options.staffCount} staff`,
    textLeft,
    textBaseline,
  );

  const ruleY = Math.max(logo ? 7.5 + logoHeight + 1.5 : 0, textBaseline + 2.5);
  doc.setDrawColor(...RULE_COLOR);
  doc.setLineWidth(0.4);
  doc.line(marginLeft, ruleY, pageWidth - marginRight, ruleY);

  return Math.max(22, ruleY + 3);
}

function drawPageFooter(
  doc: jsPDF,
  options: ExportSchedulesPdfOptions,
  marginLeft: number,
  marginRight: number,
) {
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const footerY = pageHeight - 6;

  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.2);
  doc.line(marginLeft, footerY - 3, pageWidth - marginRight, footerY - 3);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(6.5);
  doc.setTextColor(...FOOTER_TEXT);
  doc.text(
    buildSchedulesInternalDocumentLine(
      options.exportedAt,
      options.userDisplayName,
    ),
    pageWidth / 2,
    footerY,
    { align: "center" },
  );
}

function drawLegend(
  doc: jsPDF,
  labels: ScheduleDayLabel[],
  shiftTemplates: ShiftTemplate[],
  startY: number,
  marginLeft: number,
  marginRight: number,
  fontSize: number,
): number {
  const pageWidth = doc.internal.pageSize.getWidth();
  const usableWidth = pageWidth - marginLeft - marginRight;
  let x = marginLeft;
  let y = startY + 1.5;
  const chipHeight = Math.max(3.2, fontSize * 0.55);
  const rowStep = chipHeight + 1.2;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(Math.max(6, fontSize));
  doc.setTextColor(...BRAND_DARK);
  doc.text("Legend", marginLeft, y);
  y += rowStep * 0.85;

  const chips: Array<{
    abbreviation: string;
    name: string;
    bg: [number, number, number];
    fg: [number, number, number];
  }> = [];

  for (const label of labels) {
    chips.push({
      abbreviation: label.abbreviation,
      name: label.name,
      bg: parseHexColor(label.bgColor) ?? HEADER_BG,
      fg: parseHexColor(label.textColor) ?? BRAND_DARK,
    });
  }

  for (const template of shiftTemplates.filter((t) => t.isActive)) {
    chips.push({
      abbreviation: template.abbreviation,
      name: formatShiftRangeLabel(template.startTime, template.endTime),
      bg: parseHexColor(template.bgColor) ?? HEADER_BG,
      fg: parseHexColor(template.textColor) ?? BRAND_DARK,
    });
  }

  doc.setFont("helvetica", "normal");
  doc.setFontSize(Math.max(5.5, fontSize - 0.5));

  for (const chip of chips) {
    const label = `${chip.abbreviation} ${chip.name}`;
    const textWidth = doc.getTextWidth(label);
    const chipWidth = Math.min(usableWidth, textWidth + 4);

    if (x + chipWidth > pageWidth - marginRight) {
      x = marginLeft;
      y += rowStep;
    }

    doc.setFillColor(...chip.bg);
    doc.roundedRect(x, y - chipHeight + 0.8, chipWidth, chipHeight, 0.4, 0.4, "F");
    doc.setTextColor(...chip.fg);
    doc.text(label, x + 1.5, y);
    x += chipWidth + 1.5;
  }

  return y + 2;
}

function renderPdf(
  options: ExportSchedulesPdfOptions,
  logo: PdfLogoAsset | null,
  days: WeekDayColumn[],
  weekLabel: string,
  orderedBlocks: SchedulesPdfDepartmentBlock[],
  fontSize: number,
  cellPadding: number,
): jsPDF {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  const margin = { top: 0, right: 8, bottom: 12, left: 8 };
  const viewLabel = options.view === "roster" ? "Roster" : "Sections";
  const departmentLabels = orderedBlocks.map((block) => block.departmentLabel);
  const staffCount = orderedBlocks.reduce(
    (sum, block) => sum + block.staff.length,
    0,
  );

  const startY = drawPageHeader(
    doc,
    {
      venueName: options.venueName,
      weekLabel,
      viewLabel,
      departmentLabels,
      staffCount,
    },
    logo,
    margin.left,
    margin.right,
  );

  const { body, meta } = buildCombinedBody(
    orderedBlocks,
    options.view,
    days,
    options.labels,
    options.shiftTemplates,
  );

  const head = [
    [
      "Staff",
      "Position",
      ...days.map((day) => `${day.weekdayLabel}\n${day.dayLabel}`),
    ],
  ];

  const pageWidth = doc.internal.pageSize.getWidth();
  const tableWidth = pageWidth - margin.left - margin.right;
  const staffWidth = 48;
  const positionWidth = 26;
  const dayWidth = (tableWidth - staffWidth - positionWidth) / DAY_COL_COUNT;

  autoTable(doc, {
    startY,
    margin,
    tableWidth,
    theme: "grid",
    pageBreak: "avoid",
    rowPageBreak: "avoid",
    showHead: "firstPage",
    styles: {
      font: "helvetica",
      fontSize,
      cellPadding,
      lineColor: [210, 210, 210],
      lineWidth: 0.1,
      textColor: BRAND_DARK,
      valign: "middle",
      overflow: "linebreak",
      minCellHeight: Math.max(4.2, fontSize * 0.75),
    },
    headStyles: {
      fillColor: HEADER_BG,
      textColor: BRAND_DARK,
      fontStyle: "bold",
      halign: "center",
      valign: "middle",
      fontSize: Math.max(5.5, fontSize - 0.5),
      cellPadding: Math.max(0.4, cellPadding),
    },
    columnStyles: {
      0: { cellWidth: staffWidth, halign: "left", fontStyle: "bold" },
      1: { cellWidth: positionWidth, halign: "left", fontStyle: "normal" },
      2: { cellWidth: dayWidth, halign: "center" },
      3: { cellWidth: dayWidth, halign: "center" },
      4: { cellWidth: dayWidth, halign: "center" },
      5: { cellWidth: dayWidth,halign: "center" },
      6: { cellWidth: dayWidth,halign: "center" },
      7: { cellWidth: dayWidth,halign: "center" },
      8: { cellWidth: dayWidth,halign: "center" },
    },
    head,
    body,
    didParseCell(data) {
      if (data.section === "head") {
        const dayIndex = data.column.index - META_COL_COUNT;
        if (
          dayIndex >= 0 &&
          dayIndex < days.length &&
          days[dayIndex]?.isPublicHoliday
        ) {
          data.cell.styles.fillColor = PH_HEADER_BG;
          data.cell.styles.textColor = PH_HEADER_TEXT;
        }
        return;
      }

      if (data.section !== "body") return;
      const rowMeta = meta[data.row.index];
      if (!rowMeta) return;

      if (rowMeta.kind === "department") {
        data.cell.styles.fillColor = DEPT_BAND_BG;
        data.cell.styles.textColor = [255, 255, 255];
        data.cell.styles.fontStyle = "bold";
        data.cell.styles.halign = "left";
        data.cell.styles.fontSize = Math.max(6.5, fontSize + 0.5);
        return;
      }

      if (rowMeta.kind === "section") {
        data.cell.styles.fillColor = SECTION_BAND_BG;
        data.cell.styles.textColor = BRAND_DARK;
        data.cell.styles.fontStyle = "bold";
        data.cell.styles.halign = "left";
        data.cell.styles.fontSize = Math.max(6, fontSize);
        return;
      }

      if (rowMeta.kind === "note") {
        data.cell.styles.fillColor = [252, 252, 250];
        data.cell.styles.textColor = [130, 130, 130];
        data.cell.styles.fontStyle = "italic";
        data.cell.styles.halign = "left";
        return;
      }

      if (data.column.index < META_COL_COUNT) {
        data.cell.styles.fillColor = STAFF_META_BG;
        if (data.column.index === 0) {
          data.cell.styles.fontStyle = "bold";
        }
        return;
      }

      const dayIndex = data.column.index - META_COL_COUNT;
      const presentation = rowMeta.presentationByDay[dayIndex];
      if (!presentation) {
        data.cell.styles.fillColor = days[dayIndex]?.isPublicHoliday
          ? PH_BODY_BG
          : EMPTY_CELL_BG;
        data.cell.styles.textColor = [160, 160, 160];
        return;
      }

      data.cell.styles.fillColor =
        parseHexColor(presentation.bgColor) ?? HEADER_BG;
      data.cell.styles.textColor =
        parseHexColor(presentation.textColor) ?? BRAND_DARK;
      data.cell.styles.fontStyle = "bold";
      data.cell.styles.fontSize = Math.max(5.5, fontSize - 0.5);
    },
    didDrawPage() {
      drawPageFooter(doc, options, margin.left, margin.right);
    },
  });

  const table = (
    doc as unknown as {
      lastAutoTable?: { finalY: number };
    }
  ).lastAutoTable;
  const legendY = (table?.finalY ?? startY) + 2;
  const pageHeight = doc.internal.pageSize.getHeight();
  if (legendY + 16 < pageHeight - margin.bottom) {
    drawLegend(
      doc,
      options.labels,
      options.shiftTemplates,
      legendY,
      margin.left,
      margin.right,
      Math.max(5.5, fontSize - 0.5),
    );
  }

  return doc;
}

export async function exportSchedulesPdf(
  options: ExportSchedulesPdfOptions,
): Promise<void> {
  if (!options.view) {
    throw new Error("Select a view.");
  }
  if (!Object.values(options.departments).some(Boolean)) {
    throw new Error("Select at least one department.");
  }
  if (options.blocks.length === 0) {
    throw new Error("No schedule data to publish.");
  }

  const monday = getMondayForWeekOffset(options.weekOffset);
  const days = getWeekDayColumns(monday, options.publicHolidayByDate);
  const weekLabel = formatWeekRangeLabel(monday);
  const logo = options.venueLogoUrl
    ? await loadPdfLogoAsset(options.venueLogoUrl)
    : null;

  const orderedBlocks = SCHEDULE_DEPARTMENTS.map((d) => d.key)
    .filter((key) => options.departments[key])
    .map((key) => options.blocks.find((entry) => entry.departmentKey === key))
    .filter((block): block is SchedulesPdfDepartmentBlock => Boolean(block));

  let fontSize = 7;
  let cellPadding = 1.1;
  let doc = renderPdf(
    options,
    logo,
    days,
    weekLabel,
    orderedBlocks,
    fontSize,
    cellPadding,
  );

  while (doc.getNumberOfPages() > 1 && fontSize > 4) {
    fontSize -= 0.4;
    cellPadding = Math.max(0.25, cellPadding - 0.08);
    doc = renderPdf(
      options,
      logo,
      days,
      weekLabel,
      orderedBlocks,
      fontSize,
      cellPadding,
    );
  }

  doc.save(
    buildSchedulesPdfFilename(
      options.venueName,
      weekLabel,
      options.view,
      options.departments,
      options.exportedAt,
    ),
  );
}

/** Map API day rows into the cell map used by the PDF/UI. */
export function scheduleDaysToCellMap(
  days: SchedulesPdfDayRow[],
  knownCodes: Set<string>,
): Record<string, ScheduleCellValue> {
  const next: Record<string, ScheduleCellValue> = {};
  for (const day of days) {
    if (!knownCodes.has(day.label_code) && day.label_code !== "LP") continue;
    const code = day.label_code === "LP" ? "AL" : day.label_code;
    if (!knownCodes.has(code)) continue;
    next[scheduleCellKey(day.staff_id, day.work_date)] = {
      labelCode: code,
      shiftTemplateId:
        code === "SHIFT" ? (day.shift_template_id ?? null) : null,
    };
  }
  return next;
}
