"use client";

import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import { splitGrossAtVatRate } from "@/lib/hr/certification-costs";
import { loadPayslipPdfLogo } from "@/lib/hr/payslip-pdf";
import {
  buildExcelWorkbook,
  downloadExcelWorkbook,
} from "@/lib/sales/excel-utils";
import type { VisaExpenseMonth } from "@/lib/hr/types";

export type VisaExpensesExportFormat = "pdf" | "excel";

/** totals = category summary only; detailed = one row per employee expense. */
export type VisaExpensesExportDetail = "totals" | "detailed";

export type ExportVisaExpensesOptions = {
  venueName: string;
  venueLogoUrl?: string | null;
  months: VisaExpenseMonth[];
  exportedAt: Date;
  userDisplayName: string;
  detail?: VisaExpensesExportDetail;
};

const BRAND_DARK: [number, number, number] = [61, 66, 31];
const HEADER_BG: [number, number, number] = [240, 243, 221];
const TOTALS_BG: [number, number, number] = [226, 232, 200];
const FOOTER_TEXT: [number, number, number] = [110, 110, 110];

const TOTALS_HEADERS = [
  "Month",
  "Type",
  "Qty",
  "Net",
  "VAT",
  "Gross",
] as const;

const DETAIL_HEADERS = [
  "Month",
  "Type",
  "Emp no",
  "Employee",
  "Reference",
  "Date",
  "Net",
  "VAT",
  "Gross",
] as const;

function sanitizeFilenamePart(value: string): string {
  return value
    .trim()
    .replace(/[\\/:*?"<>|]/g, "")
    .replace(/\s+/g, " ");
}

function formatExportDateStamp(date: Date): string {
  const day = String(date.getDate()).padStart(2, "0");
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const year = String(date.getFullYear()).slice(-2);
  return `${day}-${month}-${year}`;
}

function formatExportTimestamp(date: Date): string {
  const day = String(date.getDate()).padStart(2, "0");
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const year = date.getFullYear();
  const hours = String(date.getHours()).padStart(2, "0");
  const minutes = String(date.getMinutes()).padStart(2, "0");
  return `${day}/${month}/${year} ${hours}:${minutes}`;
}

function formatPdfDate(value: string): string {
  const iso = value.trim().slice(0, 10);
  const match = /^(\d{4})-(\d{2})-(\d{2})$/.exec(iso);
  if (!match) return value;
  return `${match[3]}/${match[2]}/${match[1].slice(-2)}`;
}

function buildInternalDocumentLine(
  exportedAt: Date,
  userDisplayName: string,
): string {
  const name = userDisplayName.trim() || "Unknown";
  return `File created on: ${formatExportTimestamp(exportedAt)} - Generated by ${name}  |  Internal document`;
}

function pdfSafeText(value: string): string {
  return value
    .replace(/[\u2013\u2014\u2212]/g, "-")
    .replace(/[\u00B7\u2022]/g, "|")
    .replace(/[^\x20-\x7E]/g, "?");
}

function moneyPlain(amount: number): string {
  return new Intl.NumberFormat("en-AE", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  }).format(amount);
}

function lineLabel(line: VisaExpenseMonth["lines"][number]): string {
  return line.name;
}

function sortMonthsNewestFirst(
  months: VisaExpenseMonth[],
): VisaExpenseMonth[] {
  return [...months].sort((a, b) =>
    a.monthKey < b.monthKey ? 1 : a.monthKey > b.monthKey ? -1 : 0,
  );
}

export function buildVisaExpensesPeriodLabel(
  months: VisaExpenseMonth[],
): string {
  const sorted = sortMonthsNewestFirst(months);
  if (sorted.length === 0) return "No months";
  if (sorted.length === 1) return sorted[0]!.label;
  const newest = sorted[0]!;
  const oldest = sorted[sorted.length - 1]!;
  return `${oldest.label} - ${newest.label}`;
}

export function sumVisaExpenseMonths(months: VisaExpenseMonth[]): {
  totalCount: number;
  totalNet: number;
  totalVat: number;
  totalGross: number;
} {
  return months.reduce(
    (acc, m) => ({
      totalCount: acc.totalCount + m.totalCount,
      totalNet: Math.round((acc.totalNet + m.totalNet) * 100) / 100,
      totalVat: Math.round((acc.totalVat + m.totalVat) * 100) / 100,
      totalGross: Math.round((acc.totalGross + m.totalGross) * 100) / 100,
    }),
    { totalCount: 0, totalNet: 0, totalVat: 0, totalGross: 0 },
  );
}

export function buildVisaExpensesFilename(
  venueName: string,
  periodLabel: string,
  format: VisaExpensesExportFormat,
  exportedAt: Date = new Date(),
  detail: VisaExpensesExportDetail = "detailed",
): string {
  const venue = sanitizeFilenamePart(venueName);
  const period = sanitizeFilenamePart(periodLabel);
  const stamp = formatExportDateStamp(exportedAt);
  const mode = detail === "detailed" ? "Detail" : "Totals";
  const extension = format === "pdf" ? "pdf" : "xlsx";
  return `${venue} Visa Expenses ${mode} ${period} ${stamp}.${extension}`;
}

type DetailRow = {
  month: string;
  type: string;
  empNo: string;
  fullName: string;
  reference: string;
  date: string;
  net: number;
  vat: number;
  gross: number;
};

function buildTotalsBodyRows(months: VisaExpenseMonth[]): string[][] {
  const rows: string[][] = [];
  for (const month of sortMonthsNewestFirst(months)) {
    for (const line of month.lines) {
      rows.push([
        month.label,
        lineLabel(line),
        String(line.count),
        moneyPlain(line.net),
        moneyPlain(line.vat),
        moneyPlain(line.gross),
      ]);
    }
  }
  return rows;
}

function buildDetailRows(months: VisaExpenseMonth[]): DetailRow[] {
  const rows: DetailRow[] = [];
  for (const month of sortMonthsNewestFirst(months)) {
    for (const line of month.lines) {
      for (const person of line.staff) {
        const costs = splitGrossAtVatRate(person.value);
        rows.push({
          month: month.label,
          type: lineLabel(line),
          empNo: person.empNo || "",
          fullName: person.fullName || "",
          reference: person.reference || "",
          date: person.issuedAt || "",
          net: costs.net,
          vat: costs.vat,
          gross: costs.gross,
        });
      }
    }
  }
  return rows;
}

function drawFooter(
  doc: jsPDF,
  exportedAt: Date,
  userDisplayName: string,
  marginLeft: number,
  marginRight: number,
): void {
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageCount = doc.getNumberOfPages();
  for (let page = 1; page <= pageCount; page += 1) {
    doc.setPage(page);
    doc.setFontSize(7.5);
    doc.setTextColor(...FOOTER_TEXT);
    doc.text(
      pdfSafeText(buildInternalDocumentLine(exportedAt, userDisplayName)),
      marginLeft,
      doc.internal.pageSize.getHeight() - 8,
    );
    doc.text(
      `Page ${page} of ${pageCount}`,
      pageWidth - marginRight,
      doc.internal.pageSize.getHeight() - 8,
      { align: "right" },
    );
  }
}

async function exportVisaExpensesPdf(
  options: ExportVisaExpensesOptions,
): Promise<void> {
  const {
    venueName,
    venueLogoUrl,
    months,
    exportedAt,
    userDisplayName,
    detail = "detailed",
  } = options;
  if (months.length === 0) {
    throw new Error("Select at least one month.");
  }

  const periodLabel = buildVisaExpensesPeriodLabel(months);
  const totals = sumVisaExpenseMonths(months);
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const marginLeft = 12;
  const marginRight = 12;
  const pageWidth = doc.internal.pageSize.getWidth();
  const logo = venueLogoUrl ? await loadPayslipPdfLogo(venueLogoUrl) : null;

  let y = 12;
  if (logo && logo.width > 0 && logo.height > 0) {
    const logoHeight = 8;
    const logoWidth = Math.min(
      32,
      (logo.width / logo.height) * logoHeight,
    );
    doc.addImage(
      logo.dataUrl,
      logo.format,
      marginLeft,
      y - 2,
      logoWidth,
      logoWidth / (logo.width / logo.height),
    );
  }

  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(...BRAND_DARK);
  doc.text(pdfSafeText(venueName), pageWidth - marginRight, y, {
    align: "right",
  });
  y += 6;
  doc.setFontSize(12);
  doc.text(
    detail === "detailed" ? "Visa expenses (detail)" : "Visa expenses (totals)",
    pageWidth - marginRight,
    y,
    { align: "right" },
  );
  y += 5;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(80, 80, 80);
  doc.text(
    pdfSafeText(
      `${periodLabel}${months.length > 1 ? `  (${months.length} months)` : ""}`,
    ),
    pageWidth - marginRight,
    y,
    { align: "right" },
  );
  y += 8;

  if (detail === "detailed") {
    const detailRows = buildDetailRows(months);
    autoTable(doc, {
      startY: y,
      head: [Array.from(DETAIL_HEADERS)],
      body: detailRows.map((row) =>
        [
          row.month,
          row.type,
          row.empNo,
          row.fullName,
          row.reference,
          row.date ? formatPdfDate(row.date) : "",
          moneyPlain(row.net),
          moneyPlain(row.vat),
          moneyPlain(row.gross),
        ].map(pdfSafeText),
      ),
      foot: [
        [
          "Total",
          "",
          "",
          "",
          "",
          String(totals.totalCount),
          moneyPlain(totals.totalNet),
          moneyPlain(totals.totalVat),
          moneyPlain(totals.totalGross),
        ].map(pdfSafeText),
      ],
      theme: "grid",
      styles: {
        fontSize: 7,
        cellPadding: 1.4,
        textColor: BRAND_DARK,
        lineColor: [200, 200, 190],
        lineWidth: 0.15,
        overflow: "linebreak",
        valign: "middle",
      },
      headStyles: {
        fillColor: HEADER_BG,
        textColor: BRAND_DARK,
        fontStyle: "bold",
        fontSize: 6.5,
      },
      footStyles: {
        fillColor: TOTALS_BG,
        textColor: BRAND_DARK,
        fontStyle: "bold",
        fontSize: 7,
      },
      columnStyles: {
        0: { cellWidth: 22 },
        1: { cellWidth: 24 },
        2: { cellWidth: 14 },
        3: { cellWidth: 28 },
        4: { cellWidth: 18 },
        5: { cellWidth: 14 },
        6: { halign: "right", cellWidth: 16 },
        7: { halign: "right", cellWidth: 14 },
        8: { halign: "right", cellWidth: 16 },
      },
      margin: { left: marginLeft, right: marginRight, bottom: 14 },
    });
  } else {
    autoTable(doc, {
      startY: y,
      head: [Array.from(TOTALS_HEADERS)],
      body: buildTotalsBodyRows(months).map((row) => row.map(pdfSafeText)),
      foot: [
        [
          "Total",
          "",
          String(totals.totalCount),
          moneyPlain(totals.totalNet),
          moneyPlain(totals.totalVat),
          moneyPlain(totals.totalGross),
        ].map(pdfSafeText),
      ],
      theme: "grid",
      styles: {
        fontSize: 8.5,
        cellPadding: 2,
        textColor: BRAND_DARK,
        lineColor: [200, 200, 190],
        lineWidth: 0.2,
      },
      headStyles: {
        fillColor: HEADER_BG,
        textColor: BRAND_DARK,
        fontStyle: "bold",
      },
      footStyles: {
        fillColor: TOTALS_BG,
        textColor: BRAND_DARK,
        fontStyle: "bold",
      },
      columnStyles: {
        0: { cellWidth: 28 },
        1: { cellWidth: "auto" },
        2: { halign: "right", cellWidth: 16 },
        3: { halign: "right", cellWidth: 26 },
        4: { halign: "right", cellWidth: 24 },
        5: {halign: "right", cellWidth: 26 },
      },
      margin: { left: marginLeft, right: marginRight, bottom: 14 },
    });
  }

  drawFooter(doc, exportedAt, userDisplayName, marginLeft, marginRight);

  doc.save(
    buildVisaExpensesFilename(
      venueName,
      periodLabel,
      "pdf",
      exportedAt,
      detail,
    ),
  );
}

async function exportVisaExpensesExcel(
  options: ExportVisaExpensesOptions,
): Promise<void> {
  const {
    venueName,
    months,
    exportedAt,
    userDisplayName,
    detail = "detailed",
  } = options;
  if (months.length === 0) {
    throw new Error("Select at least one month.");
  }

  const periodLabel = buildVisaExpensesPeriodLabel(months);
  const totals = sumVisaExpenseMonths(months);

  const meta = [
    ["Visa expenses"],
    ["Venue", venueName],
    ["Period", periodLabel],
    ["Months", String(months.length)],
    ["Mode", detail === "detailed" ? "Detailed expenses" : "Totals only"],
    ["Generated", formatExportTimestamp(exportedAt)],
    ["Generated by", userDisplayName],
    [],
    [
      detail === "detailed"
        ? "Amounts are AED. Each row is one employee expense reference (VAT-inclusive gross)."
        : "Amounts are AED. Category totals by month (VAT-inclusive).",
    ],
  ];

  if (detail === "detailed") {
    const detailRows = buildDetailRows(months);
    const dataRows = detailRows.map((row) => [
      row.month,
      row.type,
      row.empNo,
      row.fullName,
      row.reference,
      row.date,
      Number(row.net.toFixed(2)),
      Number(row.vat.toFixed(2)),
      Number(row.gross.toFixed(2)),
    ]);
    dataRows.push([
      "Total",
      "",
      "",
      "",
      "",
      String(totals.totalCount),
      Number(totals.totalNet.toFixed(2)),
      Number(totals.totalVat.toFixed(2)),
      Number(totals.totalGross.toFixed(2)),
    ]);

    const workbook = await buildExcelWorkbook(
      "Expenses",
      Array.from(DETAIL_HEADERS),
      dataRows,
      meta,
    );

    await downloadExcelWorkbook(
      workbook,
      buildVisaExpensesFilename(
        venueName,
        periodLabel,
        "excel",
        exportedAt,
        detail,
      ),
    );
    return;
  }

  const dataRows: (string | number)[][] = [];
  for (const month of sortMonthsNewestFirst(months)) {
    for (const line of month.lines) {
      dataRows.push([
        month.label,
        lineLabel(line),
        line.count,
        Number(line.net.toFixed(2)),
        Number(line.vat.toFixed(2)),
        Number(line.gross.toFixed(2)),
      ]);
    }
  }
  dataRows.push([
    "Total",
    "",
    totals.totalCount,
    Number(totals.totalNet.toFixed(2)),
    Number(totals.totalVat.toFixed(2)),
    Number(totals.totalGross.toFixed(2)),
  ]);

  const workbook = await buildExcelWorkbook(
    "Expenses",
    Array.from(TOTALS_HEADERS),
    dataRows,
    meta,
  );

  await downloadExcelWorkbook(
    workbook,
    buildVisaExpensesFilename(
      venueName,
      periodLabel,
      "excel",
      exportedAt,
      detail,
    ),
  );
}

export async function exportVisaExpenses(
  format: VisaExpensesExportFormat,
  options: ExportVisaExpensesOptions,
): Promise<void> {
  if (format === "pdf") {
    await exportVisaExpensesPdf(options);
    return;
  }
  await exportVisaExpensesExcel(options);
}

/** Prefer current month when present, else newest available. */
export function defaultVisaExpenseMonthKey(
  months: VisaExpenseMonth[],
): string {
  if (months.length === 0) return "";
  const now = new Date();
  const currentKey = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}`;
  if (months.some((m) => m.monthKey === currentKey)) return currentKey;
  return (
    [...months].sort((a, b) =>
      a.monthKey < b.monthKey ? 1 : a.monthKey > b.monthKey ? -1 : 0,
    )[0]?.monthKey ?? ""
  );
}
