"use client";

import {
  buildPdfHeaders,
  exportPersonName,
  filterSummaryLine,
  pdfColumnWidthPercents,
  pdfNumericColumnIndexes,
  pdfRowCells,
  type VisaEmployeesExportFilters,
  type VisaEmployeesOptionalColumn,
} from "@/lib/hr/visa-employees-export";
import type { VisaEmployeeRow } from "@/lib/hr/types";

type VisaEmployeesPdfPreviewProps = {
  venueName: string;
  venueAddress?: string | null;
  venueLogoUrl?: string | null;
  rows: VisaEmployeeRow[];
  filters?: VisaEmployeesExportFilters | null;
  optionalColumns?: VisaEmployeesOptionalColumn[];
  userDisplayName: string;
  exportedAt?: Date;
};

function formatPreviewTimestamp(date: Date): string {
  const day = String(date.getDate()).padStart(2, "0");
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const year = date.getFullYear();
  const hours = String(date.getHours()).padStart(2, "0");
  const minutes = String(date.getMinutes()).padStart(2, "0");
  return `${day}/${month}/${year} ${hours}:${minutes}`;
}

/** Live A4 landscape mock of the PDF — used in the export dialog for visual editing. */
export function VisaEmployeesPdfPreview({
  venueName,
  venueAddress,
  venueLogoUrl,
  rows,
  filters,
  optionalColumns = [],
  userDisplayName,
  exportedAt = new Date(),
}: VisaEmployeesPdfPreviewProps) {
  const summary = filterSummaryLine(filters);
  const address = venueAddress?.trim() || "";
  const personName = exportPersonName(userDisplayName);
  const footerMeta = `File created on: ${formatPreviewTimestamp(exportedAt)} - Generated by ${personName}  |  Confidential  |  Internal document`;
  const footerVenue = address ? `${venueName}  ·  ${address}` : venueName;
  const headers = buildPdfHeaders(optionalColumns);
  const widthPercents = pdfColumnWidthPercents(optionalColumns);
  const numericCols = pdfNumericColumnIndexes(optionalColumns);
  const compact = optionalColumns.length >= 4;

  return (
    <div
      className="visa-employees-pdf-preview flex h-full w-full flex-col bg-white text-[#3D421F] shadow-md"
      style={{
        boxSizing: "border-box",
        padding: "10mm",
        fontFamily: "Helvetica, Arial, sans-serif",
      }}
    >
      <header className="mb-[1.2%]">
        <div className="flex items-start justify-between gap-4">
          <div className="flex min-w-0 flex-1 items-start gap-3">
            {venueLogoUrl ? (
              // eslint-disable-next-line @next/next/no-img-element
              <img
                src={venueLogoUrl}
                alt=""
                className="h-[7%] max-h-9 w-auto object-contain"
              />
            ) : null}
            <div className="min-w-0 flex-1">
              <div
                className="truncate text-[clamp(11px,1.35vw,16px)] font-bold leading-tight"
                style={{ fontFamily: "Times New Roman, Times, serif" }}
              >
                {venueName}
              </div>
              {address ? (
                <div className="mt-0.5 text-[clamp(7px,0.75vw,9px)] leading-snug text-[#505050]">
                  {address}
                </div>
              ) : null}
              <div className="mt-0.5 text-[clamp(9px,0.95vw,11px)] font-bold leading-tight">
                Visa employees register
              </div>
              <div className="mt-0.5 text-[clamp(7px,0.75vw,9px)] leading-snug text-[#484e2a]">
                {rows.length} employee{rows.length === 1 ? "" : "s"}
                {"  |  "}
                {summary}
              </div>
            </div>
          </div>
          <div className="shrink-0 text-right text-[clamp(7px,0.75vw,9px)] leading-snug">
            <div className="font-bold text-[#505050]">Generated</div>
            <div>{formatPreviewTimestamp(exportedAt)}</div>
            <div className="mt-1 font-bold text-[#505050]">Generated by</div>
            <div className="max-w-[140px] truncate">{personName}</div>
          </div>
        </div>
        <div className="mt-2 h-[1.2px] bg-[#3D421F]" />
      </header>

      <div className="min-h-0 flex-1 overflow-hidden">
        <table className="w-full table-fixed border-collapse text-left">
          <colgroup>
            {widthPercents.map((pct, index) => (
              <col key={`col-${index}`} style={{ width: `${pct}%` }} />
            ))}
          </colgroup>
          <thead>
            <tr className="bg-[#F0F3DD]">
              {headers.map((header) => (
                <th
                  key={header}
                  className={`border border-[#c8c8be] px-1 py-0.5 font-bold uppercase tracking-wide ${
                    compact ? "text-[6.5px]" : "text-[7.5px]"
                  }`}
                >
                  {header}
                </th>
              ))}
            </tr>
          </thead>
          <tbody>
            {rows.map((row, index) => {
              const cells = pdfRowCells(row, optionalColumns);
              return (
                <tr
                  key={row.staff.id}
                  className={index % 2 === 1 ? "bg-[#fafbf6]" : "bg-white"}
                >
                  {cells.map((cell, cellIndex) => (
                    <td
                      key={`${row.staff.id}-${cellIndex}`}
                      className={`break-words border border-[#c8c8be] px-1 py-0.5 leading-snug ${
                        compact ? "text-[7px]" : "text-[8px]"
                      } ${cellIndex === 0 ? "font-semibold" : ""} ${
                        numericCols.has(cellIndex)
                          ? "text-right tabular-nums"
                          : ""
                      }`}
                    >
                      {cell || "—"}
                    </td>
                  ))}
                </tr>
              );
            })}
          </tbody>
        </table>

        {rows.length === 0 ? (
          <p className="mt-6 text-center text-[10px] text-black/45">
            No employees match the selected filters.
          </p>
        ) : null}
      </div>

      <footer className="mt-auto pt-1">
        <div className="mb-1 h-px bg-[#c8c8c8]" />
        <div className="text-[clamp(6.5px,0.65vw,7.5px)] leading-snug text-[#6e6e6e]">
          <div className="truncate">{footerVenue}</div>
          <div className="truncate">
            Unauthorized copying or disclosure is prohibited.
          </div>
          <div className="mt-0.5 flex items-end justify-between gap-3">
            <span className="min-w-0 flex-1 truncate">{footerMeta}</span>
            <span className="shrink-0">Page 1</span>
          </div>
        </div>
      </footer>
    </div>
  );
}
