import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import { formatDisplayDate } from "@/lib/dates/display";
import {
  groupCashExpenseLinesByDate,
} from "@/lib/sales/cash-expenses-calculations";
import type { VenueCashExpenseLineRecord } from "@/lib/sales/cash-expenses-types";
import {
  formatMoney,
  formatMonthLabel,
  getWeekDayLabel,
} from "@/lib/sales/daily-sales-calculations";
import {
  buildExcelWorkbook,
  downloadExcelWorkbook,
} from "@/lib/sales/excel-utils";
import type { CashJournalReportMonth } from "@/lib/sales/cash-journal-report";

export type CashJournalReportExportFormat = "pdf" | "excel";

export type ExportCashJournalReportOptions = {
  venueName: string;
  venueLogoUrl?: string | null;
  report: CashJournalReportMonth;
  expenseLines?: VenueCashExpenseLineRecord[];
  exportedAt: Date;
  userDisplayName: string;
};

type PdfLogoAsset = {
  dataUrl: string;
  format: "PNG" | "JPEG" | "WEBP";
  width: number;
  height: number;
};

const PDF_REPORT_TITLE = "Cash Journal";
const PDF_REPORT_SUBTITLE =
  "Daily open till, withdraw, cash sales, cash gratuity, expenses, deposit, closing till, and balance";

const BRAND_DARK: [number, number, number] = [61, 66, 31];
const HEADER_BG: [number, number, number] = [240, 243, 221];
const TOTALS_BG: [number, number, number] = [226, 232, 200];
const FOOTER_TEXT: [number, number, number] = [120, 120, 120];

const TABLE_HEADERS = [
  "Date",
  "Day",
  "Open till",
  "Cash Bank withdraw",
  "Cash sales",
  "Cash gratuity",
  "Cash expenses",
  "Cash Bank deposit",
  "Closing till",
  "Balance",
  "Comments",
] as const;

const EXPENSE_REFERENCE_HEADERS = [
  "Date",
  "Day",
  "Description",
  "Gross",
  "VAT",
  "Net",
  "PChase Portal",
] as const;

function expenseLinesForReportMonth(
  report: CashJournalReportMonth,
  expenseLines: VenueCashExpenseLineRecord[],
): VenueCashExpenseLineRecord[] {
  const monthDates = new Set(report.rows.map((row) => row.saleDate));
  return expenseLines.filter((line) => monthDates.has(line.sale_date));
}

function buildExpenseReferenceBodyRows(
  report: CashJournalReportMonth,
  expenseLines: VenueCashExpenseLineRecord[],
): string[][] {
  const monthLines = expenseLinesForReportMonth(report, expenseLines);
  const byDate = groupCashExpenseLinesByDate(monthLines);
  const rows: string[][] = [];

  for (const journalRow of report.rows) {
    const lines = byDate[journalRow.saleDate] ?? [];
    if (lines.length === 0 && journalRow.cashExpensesGs === 0) continue;

    if (lines.length === 0) {
      rows.push([
        formatDisplayDate(journalRow.saleDate),
        journalRow.weekDay,
        "(No references recorded)",
        "—",
        "—",
        "—",
        "—",
      ]);
      continue;
    }

    for (const line of lines) {
      rows.push([
        formatDisplayDate(journalRow.saleDate),
        journalRow.weekDay || getWeekDayLabel(journalRow.saleDate),
        line.description.trim() || "—",
        formatMoney(line.grossGs),
        formatMoney(line.vatGs),
        formatMoney(line.netGs),
        line.pchasePortal ? "Yes" : "No",
      ]);
    }
  }

  return rows;
}

function sanitizeFilenamePart(value: string): string {
  return value
    .trim()
    .replace(/[\\/:*?"<>|]/g, "")
    .replace(/\s+/g, " ");
}

function formatExportDateStamp(date: Date): string {
  const day = String(date.getDate()).padStart(2, "0");
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const year = String(date.getFullYear()).slice(-2);
  return `${day}-${month}-${year}`;
}

function formatExportTimestamp(date: Date): string {
  const day = String(date.getDate()).padStart(2, "0");
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const year = date.getFullYear();
  const hours = String(date.getHours()).padStart(2, "0");
  const minutes = String(date.getMinutes()).padStart(2, "0");
  return `${day}/${month}/${year} ${hours}:${minutes}`;
}

export function buildCashJournalReportConfidentialityLine(
  exportedAt: Date,
  userDisplayName: string,
): string {
  const name = userDisplayName.trim() || "Unknown";
  return `File created on: ${formatExportTimestamp(exportedAt)} — Generated by ${name}   |   INTERNAL CONFIDENTIAL DOCUMENT   |   All rights reserved`;
}

export function buildCashJournalReportFilename(
  venueName: string,
  monthKey: string,
  format: CashJournalReportExportFormat,
  exportedAt: Date = new Date(),
): string {
  const venue = sanitizeFilenamePart(venueName);
  const month = sanitizeFilenamePart(formatMonthLabel(monthKey));
  const stamp = formatExportDateStamp(exportedAt);
  const extension = format === "pdf" ? "pdf" : "xlsx";
  return `${venue} ${PDF_REPORT_TITLE} ${month} ${stamp}.${extension}`;
}

async function loadPdfLogoAsset(url: string): Promise<PdfLogoAsset | null> {
  if (typeof window === "undefined") return null;

  try {
    const response = await fetch(url);
    if (!response.ok) return null;

    const blob = await response.blob();

    if (blob.type.includes("svg") || url.endsWith(".svg")) {
      const svgText = await blob.text();
      const svgBlob = new Blob([svgText], {
        type: "image/svg+xml;charset=utf-8",
      });
      const objectUrl = URL.createObjectURL(svgBlob);

      try {
        return await new Promise<PdfLogoAsset | null>((resolve) => {
          const image = new Image();
          image.onload = () => {
            const canvas = document.createElement("canvas");
            canvas.width = image.naturalWidth || 400;
            canvas.height = image.naturalHeight || 400;
            const context = canvas.getContext("2d");
            URL.revokeObjectURL(objectUrl);

            if (!context) {
              resolve(null);
              return;
            }

            context.drawImage(image, 0, 0, canvas.width, canvas.height);
            resolve({
              dataUrl: canvas.toDataURL("image/png"),
              format: "PNG",
              width: canvas.width,
              height: canvas.height,
            });
          };
          image.onerror = () => {
            URL.revokeObjectURL(objectUrl);
            resolve(null);
          };
          image.src = objectUrl;
        });
      } catch {
        URL.revokeObjectURL(objectUrl);
        return null;
      }
    }

    const dataUrl = await new Promise<string>((resolve, reject) => {
      const reader = new FileReader();
      reader.onload = () => resolve(String(reader.result));
      reader.onerror = () => reject(reader.error);
      reader.readAsDataURL(blob);
    });

    const format: PdfLogoAsset["format"] = blob.type.includes("jpeg")
      ? "JPEG"
      : blob.type.includes("webp")
        ? "WEBP"
        : "PNG";

    return await new Promise<PdfLogoAsset | null>((resolve) => {
      const image = new Image();
      image.onload = () => {
        resolve({
          dataUrl,
          format,
          width: image.naturalWidth || 400,
          height: image.naturalHeight || 400,
        });
      };
      image.onerror = () => resolve(null);
      image.src = dataUrl;
    });
  } catch {
    return null;
  }
}

function drawPageFooter(
  doc: jsPDF,
  options: ExportCashJournalReportOptions,
  marginLeft: number,
  marginRight: number,
): void {
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const footerY = pageHeight - 8;

  doc.setDrawColor(210, 210, 210);
  doc.setLineWidth(0.2);
  doc.line(marginLeft, footerY - 4, pageWidth - marginRight, footerY - 4);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(6.5);
  doc.setTextColor(...FOOTER_TEXT);
  doc.text(
    buildCashJournalReportConfidentialityLine(
      options.exportedAt,
      options.userDisplayName,
    ),
    pageWidth / 2,
    footerY,
    { align: "center" },
  );
}

function moneyBodyRow(report: CashJournalReportMonth["rows"][number]) {
  return [
    formatDisplayDate(report.saleDate),
    report.weekDay,
    formatMoney(report.openTillGs),
    formatMoney(report.cashWithdrawGs),
    formatMoney(report.totalCashSalesGs),
    formatMoney(report.cashGratuityGs),
    formatMoney(report.cashExpensesGs),
    formatMoney(report.cashDepositGs),
    formatMoney(report.closingTillGs),
    formatMoney(report.balanceGs),
    report.comments || "—",
  ];
}

export async function exportCashJournalReportPdf(
  options: ExportCashJournalReportOptions,
): Promise<void> {
  const { venueName, venueLogoUrl, report } = options;
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const marginLeft = 8;
  const marginRight = 8;
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 12;

  const logo = venueLogoUrl ? await loadPdfLogoAsset(venueLogoUrl) : null;
  if (logo) {
    const logoHeight = 10;
    const logoWidth = Math.min(36, (logo.width / logo.height) * logoHeight);
    doc.addImage(
      logo.dataUrl,
      logo.format,
      marginLeft,
      y - 2,
      logoWidth,
      logoHeight,
      undefined,
      "FAST",
    );
  }

  doc.setFont("times", "bold");
  doc.setFontSize(15);
  doc.setTextColor(...BRAND_DARK);
  doc.text(PDF_REPORT_TITLE, pageWidth - marginRight, y + 2, {
    align: "right",
  });

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  doc.setTextColor(95, 95, 95);
  doc.text(venueName, pageWidth - marginRight, y + 8, { align: "right" });
  doc.text(report.monthLabel, pageWidth - marginRight, y + 13, {
    align: "right",
  });

  y = 26;
  doc.setDrawColor(...BRAND_DARK);
  doc.setLineWidth(0.35);
  doc.line(marginLeft, y, pageWidth - marginRight, y);
  y += 6;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  doc.setTextColor(90, 90, 90);
  doc.text(PDF_REPORT_SUBTITLE, marginLeft, y);
  y += 5;

  autoTable(doc, {
    startY: y,
    margin: { left: marginLeft, right: marginRight, bottom: 16 },
    theme: "grid",
    styles: {
      fontSize: 5.5,
      cellPadding: 0.9,
      textColor: BRAND_DARK,
      lineColor: [210, 210, 200],
      lineWidth: 0.2,
      overflow: "linebreak",
    },
    headStyles: {
      fillColor: HEADER_BG,
      textColor: BRAND_DARK,
      fontStyle: "bold",
      halign: "center",
      fontSize: 5,
      cellPadding: 0.8,
    },
    footStyles: {
      fillColor: TOTALS_BG,
      textColor: BRAND_DARK,
      fontStyle: "bold",
      fontSize: 5.5,
    },
    columnStyles: {
      0: { cellWidth: 16, halign: "left" },
      1: { cellWidth: 9, halign: "left" },
      2: { cellWidth: "auto", halign: "right" },
      3: { cellWidth: "auto", halign: "right" },
      4: { cellWidth: "auto", halign: "right" },
      5: { cellWidth: "auto", halign: "right" },
      6: { cellWidth: "auto", halign: "right" },
      7: { cellWidth: "auto", halign: "right" },
      8: { cellWidth: "auto", halign: "right" },
      9: { cellWidth: "auto", halign: "right" },
      10: { cellWidth: 22, halign: "left" },
    },
    head: [Array.from(TABLE_HEADERS)],
    body: report.rows.map(moneyBodyRow),
    foot: [
      [
        "Month total",
        `${report.summary.activeDayCount} day${report.summary.activeDayCount === 1 ? "" : "s"}`,
        formatMoney(report.summary.openTillGs),
        formatMoney(report.summary.cashWithdrawGs),
        formatMoney(report.summary.totalCashSalesGs),
        formatMoney(report.summary.cashGratuityGs),
        formatMoney(report.summary.cashExpensesGs),
        formatMoney(report.summary.cashDepositGs),
        formatMoney(report.summary.closingTillGs),
        formatMoney(report.summary.balanceGs),
        "",
      ],
    ],
    didDrawPage: () => {
      drawPageFooter(doc, options, marginLeft, marginRight);
    },
  });

  const expenseReferenceRows = buildExpenseReferenceBodyRows(
    report,
    options.expenseLines ?? [],
  );

  if (expenseReferenceRows.length > 0) {
    const lastTable = (
      doc as jsPDF & {
        lastAutoTable?: { finalY: number };
      }
    ).lastAutoTable;
    let sectionY = (lastTable?.finalY ?? y) + 10;
    const pageHeight = doc.internal.pageSize.getHeight();

    if (sectionY > pageHeight - 40) {
      doc.addPage();
      sectionY = 16;
    }

    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.setTextColor(...BRAND_DARK);
    doc.text("Cash expense references", marginLeft, sectionY);
    sectionY += 3;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(7);
    doc.setTextColor(90, 90, 90);
    doc.text(
      "Justification lines aligned with Cash expenses (description, gross, VAT, net, PChase Portal).",
      marginLeft,
      sectionY + 3,
    );
    sectionY += 7;

    autoTable(doc, {
      startY: sectionY,
      margin: { left: marginLeft, right: marginRight, bottom: 16 },
      theme: "grid",
      styles: {
        fontSize: 6,
        cellPadding: 1,
        textColor: BRAND_DARK,
        lineColor: [210, 210, 200],
        lineWidth: 0.2,
        overflow: "linebreak",
      },
      headStyles: {
        fillColor: HEADER_BG,
        textColor: BRAND_DARK,
        fontStyle: "bold",
        halign: "center",
        fontSize: 5.5,
        cellPadding: 0.9,
      },
      columnStyles: {
        0: { cellWidth: 18, halign: "left" },
        1: { cellWidth: 10, halign: "left" },
        2: { cellWidth: "auto", halign: "left" },
        3: { cellWidth: 18, halign: "right" },
        4: { cellWidth: 16, halign: "right" },
        5: { cellWidth: 16, halign: "right" },
        6: { cellWidth: 18, halign: "center" },
      },
      head: [Array.from(EXPENSE_REFERENCE_HEADERS)],
      body: expenseReferenceRows,
      didDrawPage: () => {
        drawPageFooter(doc, options, marginLeft, marginRight);
      },
    });
  }

  doc.save(
    buildCashJournalReportFilename(
      venueName,
      report.monthKey,
      "pdf",
      options.exportedAt,
    ),
  );
}

export async function exportCashJournalReportExcel(
  options: ExportCashJournalReportOptions,
): Promise<void> {
  const { venueName, report, exportedAt, userDisplayName } = options;

  const headers = Array.from(TABLE_HEADERS);
  const dataRows: (string | number)[][] = report.rows.map((row) => [
    formatDisplayDate(row.saleDate),
    row.weekDay,
    row.openTillGs,
    row.cashWithdrawGs,
    row.totalCashSalesGs,
    row.cashGratuityGs,
    row.cashExpensesGs,
    row.cashDepositGs,
    row.closingTillGs,
    row.balanceGs,
    row.comments || "",
  ]);

  dataRows.push([
    "Month total",
    `${report.summary.activeDayCount} day${report.summary.activeDayCount === 1 ? "" : "s"}`,
    report.summary.openTillGs,
    report.summary.cashWithdrawGs,
    report.summary.totalCashSalesGs,
    report.summary.cashGratuityGs,
    report.summary.cashExpensesGs,
    report.summary.cashDepositGs,
    report.summary.closingTillGs,
    report.summary.balanceGs,
    "",
  ]);

  const workbook = await buildExcelWorkbook("Cash Journal", headers, dataRows, [
    ["Cash Journal"],
    ["Venue", venueName],
    ["Month", report.monthLabel],
    ["Generated", formatExportTimestamp(exportedAt)],
    ["Generated by", userDisplayName],
    [],
    [
      "Balance = Open till + Cash Bank withdraw + Cash sales + Cash gratuity − Cash expenses − Cash Bank deposit − Closing till (target 0).",
    ],
  ]);

  const expenseReferenceRows = buildExpenseReferenceBodyRows(
    report,
    options.expenseLines ?? [],
  );
  if (expenseReferenceRows.length > 0) {
    const XLSX = await import("xlsx");
    const refsSheet = XLSX.utils.aoa_to_sheet([
      Array.from(EXPENSE_REFERENCE_HEADERS),
      ...expenseReferenceRows,
    ]);
    XLSX.utils.book_append_sheet(workbook, refsSheet, "Expense references");
  }

  await downloadExcelWorkbook(
    workbook,
    buildCashJournalReportFilename(
      venueName,
      report.monthKey,
      "excel",
      exportedAt,
    ),
  );
}

export async function exportCashJournalReport(
  format: CashJournalReportExportFormat,
  options: ExportCashJournalReportOptions,
): Promise<void> {
  if (format === "pdf") {
    await exportCashJournalReportPdf(options);
    return;
  }
  await exportCashJournalReportExcel(options);
}
