const PX_TO_MM = 25.4 / 96;
const VENUE_SECONDARY_BG = "#F0F3DD";
const MAX_CANVAS_EDGE_PX = 16384;

function sanitizeFilenamePart(value: string): string {
  return value
    .trim()
    .replace(/[\\/:*?"<>|]/g, "")
    .replace(/\s+/g, " ");
}

function formatSaleDateForFilename(isoDate: string): string {
  if (!/^\d{4}-\d{2}-\d{2}$/.test(isoDate)) return isoDate;
  const [year, month, day] = isoDate.split("-");
  return `${day}-${month}-${year.slice(-2)}`;
}

export function buildDailySnapPdfFilename(
  venueName: string,
  saleDate: string,
): string {
  const venue = sanitizeFilenamePart(venueName);
  const date = formatSaleDateForFilename(saleDate);
  return `${venue} Closing Report - Daily Snap (${date}).pdf`;
}

export function formatDailySnapExportTimestamp(date: Date): string {
  const pad = (value: number) => String(value).padStart(2, "0");
  const day = pad(date.getDate());
  const month = pad(date.getMonth() + 1);
  const year = String(date.getFullYear()).slice(-2);
  const hours = pad(date.getHours());
  const minutes = pad(date.getMinutes());
  return `${day}/${month}/${year} - ${hours}:${minutes}`;
}

export function buildDailySnapExportMetadataLine(
  exportedAt: Date,
  userDisplayName: string,
): string {
  return `File created on: ${formatDailySnapExportTimestamp(exportedAt)} - Generated by ${userDisplayName} | INTERNAL CONFIDENTIAL DOCUMENT | All rights reserved`;
}

const EXPORT_EDGE_PADDING_PX = 16;

type SavedStyle = {
  node: HTMLElement;
  overflow: string;
  overflowY: string;
  maxHeight: string;
  height: string;
  width: string;
};

type SavedElementStyle = {
  width: string;
  height: string;
  maxHeight: string;
  padding: string;
  boxSizing: string;
};

function unlockOverflowChain(element: HTMLElement): () => void {
  const saved: SavedStyle[] = [];
  let node: HTMLElement | null = element.parentElement;

  while (node && node !== document.body) {
    saved.push({
      node,
      overflow: node.style.overflow,
      overflowY: node.style.overflowY,
      maxHeight: node.style.maxHeight,
      height: node.style.height,
      width: node.style.width,
    });
    node.style.overflow = "visible";
    node.style.overflowY = "visible";
    node.style.maxHeight = "none";
    node = node.parentElement;
  }

  const savedElement: SavedElementStyle = {
    width: element.style.width,
    height: element.style.height,
    maxHeight: element.style.maxHeight,
    padding: element.style.padding,
    boxSizing: element.style.boxSizing,
  };

  const layoutWidth = Math.ceil(element.getBoundingClientRect().width);
  element.style.boxSizing = "border-box";
  element.style.width = `${layoutWidth + EXPORT_EDGE_PADDING_PX * 2}px`;
  element.style.padding = `${EXPORT_EDGE_PADDING_PX}px`;
  element.style.height = "auto";
  element.style.maxHeight = "none";

  return () => {
    element.style.width = savedElement.width;
    element.style.height = savedElement.height;
    element.style.maxHeight = savedElement.maxHeight;
    element.style.padding = savedElement.padding;
    element.style.boxSizing = savedElement.boxSizing;

    for (const entry of saved) {
      entry.node.style.overflow = entry.overflow;
      entry.node.style.overflowY = entry.overflowY;
      entry.node.style.maxHeight = entry.maxHeight;
      entry.node.style.height = entry.height;
      entry.node.style.width = entry.width;
    }
  };
}

async function waitForImages(element: HTMLElement): Promise<void> {
  await Promise.all(
    Array.from(element.querySelectorAll("img")).map(
      (img) =>
        new Promise<void>((resolve) => {
          if (img.complete) {
            resolve();
            return;
          }
          img.onload = () => resolve();
          img.onerror = () => resolve();
        }),
    ),
  );
}

function isSvgSource(src: string): boolean {
  return /\.svg($|\?)/i.test(src) || src.startsWith("data:image/svg+xml");
}

async function rasterizeImageElement(
  img: HTMLImageElement,
): Promise<string | null> {
  const width = Math.max(img.offsetWidth, img.naturalWidth, 64);
  const height = Math.max(img.offsetHeight, img.naturalHeight, 64);
  const scale = 2;

  try {
    if (isSvgSource(img.currentSrc || img.src)) {
      const response = await fetch(img.currentSrc || img.src);
      const svgText = await response.text();
      const blob = new Blob([svgText], { type: "image/svg+xml;charset=utf-8" });
      const blobUrl = URL.createObjectURL(blob);

      try {
        const svgImage = new Image();
        svgImage.width = width * scale;
        svgImage.height = height * scale;
        await new Promise<void>((resolve, reject) => {
          svgImage.onload = () => resolve();
          svgImage.onerror = () => reject(new Error("SVG load failed"));
          svgImage.src = blobUrl;
        });

        const canvas = document.createElement("canvas");
        canvas.width = width * scale;
        canvas.height = height * scale;
        const context = canvas.getContext("2d");
        if (!context) return null;
        context.drawImage(svgImage, 0, 0, canvas.width, canvas.height);
        return canvas.toDataURL("image/png");
      } finally {
        URL.revokeObjectURL(blobUrl);
      }
    }

    const canvas = document.createElement("canvas");
    canvas.width = width * scale;
    canvas.height = height * scale;
    const context = canvas.getContext("2d");
    if (!context) return null;
    context.drawImage(img, 0, 0, canvas.width, canvas.height);
    return canvas.toDataURL("image/png");
  } catch {
    return null;
  }
}

async function rasterizeExportImages(
  element: HTMLElement,
): Promise<() => void> {
  const restores: Array<{ img: HTMLImageElement; src: string }> = [];

  for (const node of element.querySelectorAll("img[data-export-logo]")) {
    if (!(node instanceof HTMLImageElement)) continue;
    const dataUrl = await rasterizeImageElement(node);
    if (!dataUrl) continue;
    restores.push({ img: node, src: node.src });
    node.src = dataUrl;
  }

  return () => {
    for (const entry of restores) {
      entry.img.src = entry.src;
    }
  };
}

/**
 * Force muted/gray text to solid black in the export clone only.
 * Leaves the brand olive, colored (green/red) deltas, and white text intact,
 * and never touches the on-screen panel.
 */
function forceGrayTextToBlack(cloneRoot: HTMLElement): void {
  const view = cloneRoot.ownerDocument.defaultView;
  if (!view) return;

  const applyToElement = (element: HTMLElement) => {
    const color = view.getComputedStyle(element).color;
    const match = color.match(/rgba?\(([^)]+)\)/i);
    if (!match) return;

    const parts = match[1].split(",").map((value) => parseFloat(value.trim()));
    const [r, g, b, a = 1] = parts;
    if ([r, g, b].some((channel) => Number.isNaN(channel))) return;

    const isGrayscale =
      Math.abs(r - g) <= 6 && Math.abs(g - b) <= 6 && Math.abs(r - b) <= 6;
    if (!isGrayscale) return;

    // Semi-transparent black (e.g. text-black/60, /50, /45) → solid black.
    if (a < 1 && r <= 30 && g <= 30 && b <= 30) {
      element.style.setProperty("color", "#000000", "important");
      return;
    }

    // Opaque mid-grays → black; skip near-white and already-dark text.
    if (a >= 1 && r >= 60 && r <= 200) {
      element.style.setProperty("color", "#000000", "important");
    }
  };

  applyToElement(cloneRoot);
  cloneRoot.querySelectorAll<HTMLElement>("*").forEach(applyToElement);
}

function prepareCloneForExport(
  sourceRoot: HTMLElement,
  cloneRoot: HTMLElement,
): void {
  cloneRoot.querySelectorAll("[data-export-hide]").forEach((node) => {
    if (node instanceof HTMLElement) {
      node.style.display = "none";
    }
  });

  forceGrayTextToBlack(cloneRoot);

  const sourceTextareas = sourceRoot.querySelectorAll("textarea");
  const cloneTextareas = cloneRoot.querySelectorAll("textarea");
  sourceTextareas.forEach((sourceTextarea, index) => {
    const cloneTextarea = cloneTextareas[index];
    if (
      !(sourceTextarea instanceof HTMLTextAreaElement) ||
      !(cloneTextarea instanceof HTMLTextAreaElement)
    ) {
      return;
    }

    const replacement = cloneTextarea.ownerDocument.createElement("div");
    replacement.textContent = sourceTextarea.value;
    replacement.style.width = "100%";
    replacement.style.minHeight = `${Math.max(sourceTextarea.scrollHeight, sourceTextarea.offsetHeight)}px`;
    replacement.style.padding = "8px 12px";
    replacement.style.border = "1px solid rgba(0, 0, 0, 0.1)";
    replacement.style.borderRadius = "6px";
    replacement.style.backgroundColor = "#ffffff";
    replacement.style.whiteSpace = "pre-wrap";
    replacement.style.wordBreak = "break-word";
    replacement.style.fontSize = "14px";
    replacement.style.lineHeight = "1.45";
    replacement.style.color = "#3D421F";
    cloneTextarea.replaceWith(replacement);
  });
}

function measureExportDimensions(element: HTMLElement): {
  width: number;
  height: number;
} {
  const width = Math.max(
    Math.ceil(element.scrollWidth),
    Math.ceil(element.getBoundingClientRect().width),
  );
  const height = Math.max(
    Math.ceil(element.scrollHeight),
    Math.ceil(element.offsetHeight),
  );

  return { width, height };
}

export type ExportDailySnapPdfOptions = {
  userDisplayName: string;
  exportedAt?: Date;
};

export async function exportDailySnapPdfFromElement(
  element: HTMLElement,
  filename: string,
  options: ExportDailySnapPdfOptions,
): Promise<void> {
  if (typeof window === "undefined") {
    throw new Error("PDF export is only available in the browser.");
  }

  const [{ default: html2canvas }, { jsPDF }] = await Promise.all([
    import("html2canvas-pro"),
    import("jspdf"),
  ]);

  const exportedAt = options.exportedAt ?? new Date();
  const metadataLine = buildDailySnapExportMetadataLine(
    exportedAt,
    options.userDisplayName,
  );

  const metadataFooter = document.createElement("div");
  metadataFooter.setAttribute("data-export-metadata", "");
  metadataFooter.style.borderTop = "1px solid rgba(0, 0, 0, 0.12)";
  metadataFooter.style.paddingTop = "12px";
  metadataFooter.style.paddingBottom = "4px";
  metadataFooter.style.textAlign = "center";
  metadataFooter.style.fontSize = "11px";
  metadataFooter.style.fontWeight = "700";
  metadataFooter.style.letterSpacing = "0.02em";
  metadataFooter.style.lineHeight = "1.5";
  metadataFooter.style.color = "rgba(0, 0, 0, 0.7)";
  metadataFooter.textContent = metadataLine;
  element.appendChild(metadataFooter);

  const restoreOverflow = unlockOverflowChain(element);
  const restoreImages = await rasterizeExportImages(element);

  try {
    element.scrollIntoView({ block: "start", inline: "nearest" });
    await new Promise<void>((resolve) => {
      requestAnimationFrame(() => requestAnimationFrame(() => resolve()));
    });
    await waitForImages(element);

    const { width, height } = measureExportDimensions(element);
    if (width <= 0 || height <= 0) {
      throw new Error("Nothing to export.");
    }

    const scale = Math.min(2, MAX_CANVAS_EDGE_PX / Math.max(width, height));

    const canvas = await html2canvas(element, {
      scale,
      width,
      height,
      windowWidth: width,
      windowHeight: height,
      scrollX: 0,
      scrollY: 0,
      useCORS: true,
      logging: false,
      backgroundColor: VENUE_SECONDARY_BG,
      onclone: (document) => {
        const root = document.querySelector("[data-daily-snap-export-root]");
        if (!(root instanceof HTMLElement)) return;
        prepareCloneForExport(element, root);
      },
    });

    if (canvas.width <= 0 || canvas.height <= 0) {
      throw new Error("Could not render the report snapshot.");
    }

    const cssWidth = canvas.width / scale;
    const cssHeight = canvas.height / scale;
    const pdfWidthMm = cssWidth * PX_TO_MM;
    const pdfHeightMm = cssHeight * PX_TO_MM;

    const doc = new jsPDF({
      unit: "mm",
      format: [pdfWidthMm, pdfHeightMm],
      compress: true,
    });

    let imageData: string;
    try {
      imageData = canvas.toDataURL("image/jpeg", 0.92);
    } catch {
      throw new Error(
        "Could not encode the report image. Try again after the page finishes loading.",
      );
    }

    doc.addImage(
      imageData,
      "JPEG",
      0,
      0,
      pdfWidthMm,
      pdfHeightMm,
      undefined,
      "FAST",
    );

    doc.save(filename);
  } finally {
    metadataFooter.remove();
    restoreImages();
    restoreOverflow();
  }
}
