import type { ComputedDailySales, VenueDailySalesInputField } from "./daily-sales-types";

export type ColumnKind = "date" | "meta" | "input" | "money" | "count" | "ratio";

export type DailySalesColumn = {
  key: string;
  label: string;
  kind: ColumnKind;
  field?: VenueDailySalesInputField;
  computedKey?: keyof ComputedDailySales;
  group: string;
  section: "fixed" | "lunch" | "dinner" | "total" | "asph" | "aps";
};

export const DAILY_SALES_SECTION_LABELS = {
  fixed: "",
  lunch: "Lunch",
  dinner: "Dinner",
  total: "Total",
  asph: "ASPH",
  aps: "APS",
} as const;

export const DAILY_SALES_COLUMNS: DailySalesColumn[] = [
  { key: "sale_date", label: "Date", kind: "date", group: "Date", section: "fixed" },
  {
    key: "weekNumber",
    label: "Week #",
    kind: "meta",
    computedKey: "weekNumber",
    group: "Week",
    section: "fixed",
  },
  {
    key: "weekDay",
    label: "Week Day",
    kind: "meta",
    computedKey: "weekDay",
    group: "Day",
    section: "fixed",
  },
  {
    key: "lunch_food_gs",
    label: "Food GS",
    kind: "input",
    field: "lunch_food_gs",
    group: "Food",
    section: "lunch",
  },
  {
    key: "lunch_beverages_gs",
    label: "Beverages GS",
    kind: "input",
    field: "lunch_beverages_gs",
    group: "Beverages",
    section: "lunch",
  },
  {
    key: "lunch_wine_gs",
    label: "Wine GS",
    kind: "input",
    field: "lunch_wine_gs",
    group: "Wine",
    section: "lunch",
  },
  {
    key: "lunch_shisha_gs",
    label: "Shisha GS",
    kind: "input",
    field: "lunch_shisha_gs",
    group: "Shisha",
    section: "lunch",
  },
  {
    key: "lunch_tobacco_gs",
    label: "Tobacco GS",
    kind: "input",
    field: "lunch_tobacco_gs",
    group: "Tobacco",
    section: "lunch",
  },
  {
    key: "lunch_others_gs",
    label: "Others GS",
    kind: "input",
    field: "lunch_others_gs",
    group: "Others",
    section: "lunch",
  },
  {
    key: "lunch_service_fees_gs",
    label: "Service Fees GS",
    kind: "input",
    field: "lunch_service_fees_gs",
    group: "Service Fees",
    section: "lunch",
  },
  {
    key: "lunchTotalGs",
    label: "Total Lunch GS",
    kind: "money",
    computedKey: "lunchTotalGs",
    group: "Total",
    section: "lunch",
  },
  {
    key: "lunch_covers",
    label: "Lunch Covers",
    kind: "input",
    field: "lunch_covers",
    group: "Covers",
    section: "lunch",
  },
  {
    key: "lunch_bookings",
    label: "Lunch Bookings",
    kind: "input",
    field: "lunch_bookings",
    group: "Bookings",
    section: "lunch",
  },
  {
    key: "dinner_food_gs",
    label: "Food GS",
    kind: "input",
    field: "dinner_food_gs",
    group: "Food",
    section: "dinner",
  },
  {
    key: "dinner_beverages_gs",
    label: "Beverages GS",
    kind: "input",
    field: "dinner_beverages_gs",
    group: "Beverages",
    section: "dinner",
  },
  {
    key: "dinner_wine_gs",
    label: "Wine GS",
    kind: "input",
    field: "dinner_wine_gs",
    group: "Wine",
    section: "dinner",
  },
  {
    key: "dinner_shisha_gs",
    label: "Shisha GS",
    kind: "input",
    field: "dinner_shisha_gs",
    group: "Shisha",
    section: "dinner",
  },
  {
    key: "dinner_tobacco_gs",
    label: "Tobacco GS",
    kind: "input",
    field: "dinner_tobacco_gs",
    group: "Tobacco",
    section: "dinner",
  },
  {
    key: "dinner_others_gs",
    label: "Others GS",
    kind: "input",
    field: "dinner_others_gs",
    group: "Others",
    section: "dinner",
  },
  {
    key: "dinner_service_fees_gs",
    label: "Service Fees GS",
    kind: "input",
    field: "dinner_service_fees_gs",
    group: "Service Fees",
    section: "dinner",
  },
  {
    key: "dinnerTotalGs",
    label: "Total Dinner GS",
    kind: "money",
    computedKey: "dinnerTotalGs",
    group: "Total",
    section: "dinner",
  },
  {
    key: "dinner_covers",
    label: "Dinner Covers",
    kind: "input",
    field: "dinner_covers",
    group: "Covers",
    section: "dinner",
  },
  {
    key: "dinner_bookings",
    label: "Dinner Bookings",
    kind: "input",
    field: "dinner_bookings",
    group: "Bookings",
    section: "dinner",
  },
  {
    key: "totalFoodGs",
    label: "Total Food GS",
    kind: "money",
    computedKey: "totalFoodGs",
    group: "Food",
    section: "total",
  },
  {
    key: "totalFoodNet",
    label: "Total Food NET",
    kind: "money",
    computedKey: "totalFoodNet",
    group: "Food",
    section: "total",
  },
  {
    key: "totalBeveragesGs",
    label: "Total Beverages GS",
    kind: "money",
    computedKey: "totalBeveragesGs",
    group: "Beverages",
    section: "total",
  },
  {
    key: "totalBeveragesNet",
    label: "Total Beverages NET",
    kind: "money",
    computedKey: "totalBeveragesNet",
    group: "Beverages",
    section: "total",
  },
  {
    key: "totalWineGs",
    label: "Total Wine GS",
    kind: "money",
    computedKey: "totalWineGs",
    group: "Wine",
    section: "total",
  },
  {
    key: "totalWineNet",
    label: "Total Wine NET",
    kind: "money",
    computedKey: "totalWineNet",
    group: "Wine",
    section: "total",
  },
  {
    key: "totalShishaGs",
    label: "Total Shisha GS",
    kind: "money",
    computedKey: "totalShishaGs",
    group: "Shisha",
    section: "total",
  },
  {
    key: "totalShishaNet",
    label: "Total Shisha NET",
    kind: "money",
    computedKey: "totalShishaNet",
    group: "Shisha",
    section: "total",
  },
  {
    key: "totalTobaccoGs",
    label: "Total Tobacco GS",
    kind: "money",
    computedKey: "totalTobaccoGs",
    group: "Tobacco",
    section: "total",
  },
  {
    key: "totalTobaccoNet",
    label: "Total Tobacco NET",
    kind: "money",
    computedKey: "totalTobaccoNet",
    group: "Tobacco",
    section: "total",
  },
  {
    key: "totalOthersGs",
    label: "Total Others GS",
    kind: "money",
    computedKey: "totalOthersGs",
    group: "Others",
    section: "total",
  },
  {
    key: "totalOthersNet",
    label: "Total Others NET",
    kind: "money",
    computedKey: "totalOthersNet",
    group: "Others",
    section: "total",
  },
  {
    key: "totalServiceFeesGs",
    label: "Total Service Fees GS",
    kind: "money",
    computedKey: "totalServiceFeesGs",
    group: "Service Fees",
    section: "total",
  },
  {
    key: "totalServiceFeesNet",
    label: "Total Service Fees NET",
    kind: "money",
    computedKey: "totalServiceFeesNet",
    group: "Service Fees",
    section: "total",
  },
  {
    key: "totalVenueGs",
    label: "Total Venue GS",
    kind: "money",
    computedKey: "totalVenueGs",
    group: "Venue",
    section: "total",
  },
  {
    key: "totalVenueNet",
    label: "Total Venue NET",
    kind: "money",
    computedKey: "totalVenueNet",
    group: "Venue",
    section: "total",
  },
  {
    key: "totalCovers",
    label: "Total Covers",
    kind: "count",
    computedKey: "totalCovers",
    group: "Covers",
    section: "total",
  },
  {
    key: "totalBookings",
    label: "Total Bookings",
    kind: "count",
    computedKey: "totalBookings",
    group: "Bookings",
    section: "total",
  },
  {
    key: "foodLunchAsph",
    label: "Food Lunch ASPH",
    kind: "ratio",
    computedKey: "foodLunchAsph",
    group: "Food",
    section: "asph",
  },
  {
    key: "foodDinnerAsph",
    label: "Food Dinner ASPH",
    kind: "ratio",
    computedKey: "foodDinnerAsph",
    group: "Food",
    section: "asph",
  },
  {
    key: "beveragesLunchAsph",
    label: "Beverages Lunch ASPH",
    kind: "ratio",
    computedKey: "beveragesLunchAsph",
    group: "Beverages",
    section: "asph",
  },
  {
    key: "beveragesDinnerAsph",
    label: "Beverages Dinner ASPH",
    kind: "ratio",
    computedKey: "beveragesDinnerAsph",
    group: "Beverages",
    section: "asph",
  },
  {
    key: "wineLunchAsph",
    label: "Wine Lunch ASPH",
    kind: "ratio",
    computedKey: "wineLunchAsph",
    group: "Wine",
    section: "asph",
  },
  {
    key: "wineDinnerAsph",
    label: "Wine Dinner ASPH",
    kind: "ratio",
    computedKey: "wineDinnerAsph",
    group: "Wine",
    section: "asph",
  },
  {
    key: "shishaLunchAsph",
    label: "Shisha Lunch ASPH",
    kind: "ratio",
    computedKey: "shishaLunchAsph",
    group: "Shisha",
    section: "asph",
  },
  {
    key: "shishaDinnerAsph",
    label: "Shisha Dinner ASPH",
    kind: "ratio",
    computedKey: "shishaDinnerAsph",
    group: "Shisha",
    section: "asph",
  },
  {
    key: "totalVenueAllDayAsph",
    label: "Total Venue All Day ASPH",
    kind: "ratio",
    computedKey: "totalVenueAllDayAsph",
    group: "Venue",
    section: "asph",
  },
  {
    key: "totalVenueLunchAsph",
    label: "Total Venue Lunch ASPH",
    kind: "ratio",
    computedKey: "totalVenueLunchAsph",
    group: "Venue",
    section: "asph",
  },
  {
    key: "totalVenueDinnerAsph",
    label: "Total Venue Dinner ASPH",
    kind: "ratio",
    computedKey: "totalVenueDinnerAsph",
    group: "Venue",
    section: "asph",
  },
  {
    key: "apsAllDay",
    label: "APS All Day",
    kind: "ratio",
    computedKey: "apsAllDay",
    group: "All Day",
    section: "aps",
  },
  {
    key: "apsLunch",
    label: "APS Lunch",
    kind: "ratio",
    computedKey: "apsLunch",
    group: "Lunch",
    section: "aps",
  },
  {
    key: "apsDinner",
    label: "APS Dinner",
    kind: "ratio",
    computedKey: "apsDinner",
    group: "Dinner",
    section: "aps",
  },
];

export function columnsForSection(
  section: DailySalesColumn["section"],
): DailySalesColumn[] {
  return DAILY_SALES_COLUMNS.filter((col) => col.section === section);
}

export function sectionColSpan(section: DailySalesColumn["section"]): number {
  return columnsForSection(section).length;
}
