import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import {
  formatCount,
  formatDisplayDate,
  formatMoney,
} from "@/lib/sales/daily-sales-calculations";
import type {
  FiguresAlertCheck,
  FiguresAlertsDay,
} from "@/lib/sales/figures-alerts-calculations";

export type FiguresAlertsPdfSections = {
  alertDays: boolean;
  balancedDays: boolean;
  includeMatchingChecks: boolean;
};

export const DEFAULT_FIGURES_ALERTS_PDF_SECTIONS: FiguresAlertsPdfSections = {
  alertDays: true,
  balancedDays: false,
  includeMatchingChecks: true,
};

type PdfLogoAsset = {
  dataUrl: string;
  format: "PNG" | "JPEG" | "WEBP";
  width: number;
  height: number;
};

const PDF_REPORT_TITLE = "Figures Alerts";
const PDF_REPORT_SUBTITLE =
  "Verification mismatches across daily sales, waiter sales, tenders, tax, and discounts";

const BRAND_DARK: [number, number, number] = [61, 66, 31];
const HEADER_BG: [number, number, number] = [240, 243, 221];
const ALERT_BG: [number, number, number] = [255, 251, 235];
const MATCH_BG: [number, number, number] = [236, 253, 245];
const FOOTER_TEXT: [number, number, number] = [120, 120, 120];
const MATCH_TEXT: [number, number, number] = [4, 120, 87];
const DIFF_TEXT: [number, number, number] = [180, 83, 9];

export type ExportFiguresAlertsPdfOptions = {
  venueName: string;
  venueLogoUrl?: string | null;
  periodLabel: string;
  days: FiguresAlertsDay[];
  sections: FiguresAlertsPdfSections;
  exportedAt: Date;
  userDisplayName: string;
};

function sanitizeFilenamePart(value: string): string {
  return value
    .trim()
    .replace(/[\\/:*?"<>|]/g, "")
    .replace(/\s+/g, " ");
}

function formatExportDateStamp(date: Date): string {
  const day = String(date.getDate()).padStart(2, "0");
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const year = String(date.getFullYear()).slice(-2);
  return `${day}-${month}-${year}`;
}

function formatExportTimestamp(date: Date): string {
  const day = String(date.getDate()).padStart(2, "0");
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const year = date.getFullYear();
  const hours = String(date.getHours()).padStart(2, "0");
  const minutes = String(date.getMinutes()).padStart(2, "0");
  return `${day}/${month}/${year} ${hours}:${minutes}`;
}

export function buildFiguresAlertsConfidentialityLine(
  exportedAt: Date,
  userDisplayName: string,
): string {
  const name = userDisplayName.trim() || "Unknown";
  return `File created on: ${formatExportTimestamp(exportedAt)} — Generated by ${name}   |   INTERNAL CONFIDENTIAL DOCUMENT   |   All rights reserved`;
}

export function buildExportSectionLabel(
  sections: FiguresAlertsPdfSections,
): string {
  const parts: string[] = [];
  if (sections.alertDays) parts.push("Alerts");
  if (sections.balancedDays) parts.push("Balanced");
  return parts.join(" & ") || "Export";
}

export function buildFiguresAlertsPdfFilename(
  venueName: string,
  periodLabel: string,
  sections: FiguresAlertsPdfSections,
  exportedAt: Date = new Date(),
): string {
  const venue = sanitizeFilenamePart(venueName);
  const period = sanitizeFilenamePart(periodLabel);
  const stamp = formatExportDateStamp(exportedAt);
  const sectionLabel = sanitizeFilenamePart(buildExportSectionLabel(sections));
  return `${venue} ${PDF_REPORT_TITLE} (${sectionLabel}) ${period} ${stamp}.pdf`;
}

async function loadPdfLogoAsset(url: string): Promise<PdfLogoAsset | null> {
  if (typeof window === "undefined") return null;

  try {
    const response = await fetch(url);
    if (!response.ok) return null;

    const blob = await response.blob();

    if (blob.type.includes("svg") || url.endsWith(".svg")) {
      const svgText = await blob.text();
      const svgBlob = new Blob([svgText], {
        type: "image/svg+xml;charset=utf-8",
      });
      const objectUrl = URL.createObjectURL(svgBlob);

      try {
        return await new Promise<PdfLogoAsset | null>((resolve) => {
          const image = new Image();
          image.onload = () => {
            const canvas = document.createElement("canvas");
            canvas.width = image.naturalWidth || 400;
            canvas.height = image.naturalHeight || 400;
            const context = canvas.getContext("2d");
            URL.revokeObjectURL(objectUrl);

            if (!context) {
              resolve(null);
              return;
            }

            context.drawImage(image, 0, 0, canvas.width, canvas.height);
            resolve({
              dataUrl: canvas.toDataURL("image/png"),
              format: "PNG",
              width: canvas.width,
              height: canvas.height,
            });
          };
          image.onerror = () => {
            URL.revokeObjectURL(objectUrl);
            resolve(null);
          };
          image.src = objectUrl;
        });
      } catch {
        URL.revokeObjectURL(objectUrl);
        return null;
      }
    }

    const dataUrl = await new Promise<string>((resolve, reject) => {
      const reader = new FileReader();
      reader.onload = () => resolve(String(reader.result));
      reader.onerror = () => reject(reader.error);
      reader.readAsDataURL(blob);
    });

    const format = blob.type.includes("jpeg")
      ? "JPEG"
      : blob.type.includes("webp")
        ? "WEBP"
        : "PNG";

    return await new Promise<PdfLogoAsset | null>((resolve) => {
      const image = new Image();
      image.onload = () =>
        resolve({
          dataUrl,
          format,
          width: image.naturalWidth,
          height: image.naturalHeight,
        });
      image.onerror = () => resolve(null);
      image.src = dataUrl;
    });
  } catch {
    return null;
  }
}

function formatPairValue(value: number, unit: "money" | "count"): string {
  if (unit === "count") return formatCount(value);
  return formatMoney(value);
}

function formatPairDiff(
  difference: number,
  unit: "money" | "count",
  matched: boolean,
): string {
  if (matched) return "—";
  if (unit === "count") {
    const sign = difference > 0 ? "+" : "";
    return `${sign}${difference}`;
  }
  const sign = difference > 0 ? "+" : "-";
  return `${sign}${formatMoney(Math.abs(difference))}`;
}

function drawPageFooter(
  doc: jsPDF,
  options: ExportFiguresAlertsPdfOptions,
  marginLeft: number,
  marginRight: number,
): void {
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const footerY = pageHeight - 8;

  doc.setDrawColor(210, 210, 210);
  doc.setLineWidth(0.2);
  doc.line(marginLeft, footerY - 4, pageWidth - marginRight, footerY - 4);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(6.5);
  doc.setTextColor(...FOOTER_TEXT);
  doc.text(
    buildFiguresAlertsConfidentialityLine(
      options.exportedAt,
      options.userDisplayName,
    ),
    pageWidth / 2,
    footerY,
    { align: "center" },
  );
}

function drawDayPageHeader(
  doc: jsPDF,
  day: FiguresAlertsDay,
  marginLeft: number,
  marginRight: number,
  logo: PdfLogoAsset | null,
): number {
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 12;

  if (logo) {
    const logoHeight = 8;
    const logoWidth = Math.min(36, (logo.width / logo.height) * logoHeight);
    doc.addImage(
      logo.dataUrl,
      logo.format,
      marginLeft,
      y - 2,
      logoWidth,
      logoHeight,
      undefined,
      "FAST",
    );
  }

  doc.setFont("times", "bold");
  doc.setFontSize(14);
  doc.setTextColor(...BRAND_DARK);
  doc.text(formatDisplayDate(day.sale_date), marginLeft, y + 10);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(95, 95, 95);
  doc.text(
    `Week ${day.weekNumber} · ${day.weekDay}`,
    marginLeft,
    y + 15,
  );

  const status = day.balanced ? "Balanced" : `${day.alertCount} alert${day.alertCount === 1 ? "" : "s"}`;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  if (day.balanced) {
    doc.setTextColor(...MATCH_TEXT);
  } else {
    doc.setTextColor(...DIFF_TEXT);
  }
  doc.text(status, pageWidth - marginRight, y + 10, { align: "right" });

  doc.setDrawColor(...BRAND_DARK);
  doc.setLineWidth(0.35);
  doc.line(marginLeft, y + 18, pageWidth - marginRight, y + 18);

  return y + 22;
}

function renderCheckBlock(
  doc: jsPDF,
  check: FiguresAlertCheck,
  startY: number,
  marginLeft: number,
  marginRight: number,
  includeMatchingDetail: boolean,
): number {
  const pageWidth = doc.internal.pageSize.getWidth();
  const contentWidth = pageWidth - marginLeft - marginRight;
  let y = startY;

  if (!check.balanced || includeMatchingDetail) {
    doc.setFillColor(...(check.balanced ? MATCH_BG : ALERT_BG));
    doc.setDrawColor(check.balanced ? 167 : 251, check.balanced ? 243 : 191, check.balanced ? 208 : 36);
    doc.setLineWidth(0.2);
    const blockTop = y;
    y += 4;

    doc.setFont("helvetica", "bold");
    doc.setFontSize(9.5);
    doc.setTextColor(...BRAND_DARK);
    doc.text(check.label, marginLeft + 2, y);
    y += 4;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(7.5);
    doc.setTextColor(100, 100, 100);
    doc.text(`Check on: ${check.pageName}`, marginLeft + 2, y);
    y += 4;

    doc.setFontSize(8.5);
    doc.setTextColor(55, 55, 55);
    const summaryLines = doc.splitTextToSize(check.summary, contentWidth - 4);
    doc.text(summaryLines, marginLeft + 2, y);
    y += summaryLines.length * 3.6 + 2;

    for (const pair of check.pairs) {
      autoTable(doc, {
        startY: y,
        margin: { left: marginLeft + 1, right: marginRight + 1 },
        tableWidth: contentWidth - 2,
        theme: "plain",
        styles: {
          fontSize: 7.5,
          cellPadding: 1.2,
          textColor: BRAND_DARK,
          lineWidth: 0,
        },
        head: [
          [
            { content: "Source A", styles: { fillColor: HEADER_BG, fontStyle: "bold" } },
            { content: "Source B", styles: { fillColor: HEADER_BG, fontStyle: "bold" } },
            {
              content: "Diff",
              styles: {
                fillColor: HEADER_BG,
                fontStyle: "bold",
                halign: "center",
              },
            },
          ],
        ],
        body: [
          [
            `${pair.left.label}\n${pair.left.page}\n${formatPairValue(pair.left.value, pair.left.unit)}`,
            `${pair.right.label}\n${pair.right.page}\n${formatPairValue(pair.right.value, pair.right.unit)}`,
            formatPairDiff(pair.difference, pair.left.unit, pair.matched),
          ],
        ],
        columnStyles: {
          0: { cellWidth: (contentWidth - 2) * 0.42 },
          1: { cellWidth: (contentWidth - 2) * 0.42 },
          2: {
            cellWidth: (contentWidth - 2) * 0.16,
            halign: "center",
            fontStyle: "bold",
            textColor: pair.matched ? MATCH_TEXT : DIFF_TEXT,
          },
        },
      });
      y = (doc as jsPDF & { lastAutoTable?: { finalY: number } }).lastAutoTable
        ?.finalY ?? y + 14;
      y += 2;
    }

    if (check.mismatches.length > 0) {
      doc.setFont("helvetica", "bold");
      doc.setFontSize(7.5);
      doc.setTextColor(...DIFF_TEXT);
      doc.text("Where it differs:", marginLeft + 2, y);
      y += 3.5;
      doc.setFont("helvetica", "normal");
      doc.setFontSize(7.5);
      for (const line of check.mismatches) {
        const wrapped = doc.splitTextToSize(`• ${line}`, contentWidth - 6);
        doc.text(wrapped, marginLeft + 4, y);
        y += wrapped.length * 3.4 + 1;
      }
    }

    const blockHeight = y - blockTop + 2;
    doc.roundedRect(marginLeft, blockTop, contentWidth, blockHeight, 1.5, 1.5, "S");
    y += 4;
  }

  return y;
}

function renderDayPage(
  doc: jsPDF,
  day: FiguresAlertsDay,
  options: ExportFiguresAlertsPdfOptions,
  logo: PdfLogoAsset | null,
  marginLeft: number,
  marginRight: number,
): void {
  let y = drawDayPageHeader(doc, day, marginLeft, marginRight, logo);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(95, 95, 95);
  doc.text(
    `${options.venueName} · Figures Alerts · ${options.periodLabel}`,
    marginLeft,
    y,
  );
  y += 4;

  doc.setFontSize(7);
  doc.setTextColor(120, 120, 120);
  const subtitleLines = doc.splitTextToSize(PDF_REPORT_SUBTITLE, 186);
  doc.text(subtitleLines, marginLeft, y);
  y += subtitleLines.length * 3.2 + 3;

  const pageHeight = doc.internal.pageSize.getHeight();
  const bottomLimit = pageHeight - 14;

  if (day.balanced && !options.sections.includeMatchingChecks) {
    doc.setFont("helvetica", "italic");
    doc.setFontSize(9);
    doc.setTextColor(...MATCH_TEXT);
    doc.text("All verification checks matched for this date.", marginLeft, y);
    drawPageFooter(doc, options, marginLeft, marginRight);
    return;
  }

  const checksToShow = day.balanced
    ? day.checks
    : [
        ...day.checks.filter((c) => !c.balanced),
        ...(options.sections.includeMatchingChecks
          ? day.checks.filter((c) => c.balanced)
          : []),
      ];

  if (checksToShow.length === 0) {
    doc.setFont("helvetica", "italic");
    doc.setFontSize(9);
    doc.setTextColor(120, 120, 120);
    doc.text("No verification data for this date.", marginLeft, y);
    drawPageFooter(doc, options, marginLeft, marginRight);
    return;
  }

  for (const check of checksToShow) {
    if (y > bottomLimit - 24) break;
    y = renderCheckBlock(
      doc,
      check,
      y,
      marginLeft,
      marginRight,
      options.sections.includeMatchingChecks,
    );
  }

  drawPageFooter(doc, options, marginLeft, marginRight);
}

function renderPdf(
  options: ExportFiguresAlertsPdfOptions,
  logo: PdfLogoAsset | null,
): jsPDF {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const marginLeft = 12;
  const marginRight = 12;

  if (options.days.length === 0) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text("No days match the selected export options.", marginLeft, 40);
    drawPageFooter(doc, options, marginLeft, marginRight);
    return doc;
  }

  for (let index = 0; index < options.days.length; index += 1) {
    if (index > 0) doc.addPage();
    renderDayPage(
      doc,
      options.days[index],
      options,
      logo,
      marginLeft,
      marginRight,
    );
  }

  return doc;
}

export async function exportFiguresAlertsPdf(
  options: ExportFiguresAlertsPdfOptions,
): Promise<void> {
  if (!options.sections.alertDays && !options.sections.balancedDays) {
    throw new Error("Select at least one day type to export.");
  }

  const logo = options.venueLogoUrl
    ? await loadPdfLogoAsset(options.venueLogoUrl)
    : null;

  const doc = renderPdf(options, logo);
  doc.save(
    buildFiguresAlertsPdfFilename(
      options.venueName,
      options.periodLabel,
      options.sections,
      options.exportedAt,
    ),
  );
}

export function filterDaysForExport(
  days: FiguresAlertsDay[],
  sections: FiguresAlertsPdfSections,
): FiguresAlertsDay[] {
  return days.filter((day) => {
    if (!day.hasActivity) return false;
    if (day.balanced) return sections.balancedDays;
    return sections.alertDays;
  });
}
