import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import { formatDisplayDate } from "@/lib/dates/display";
import {
  formatMoney,
  formatMonthLabel,
} from "@/lib/sales/daily-sales-calculations";
import {
  buildExcelWorkbook,
  downloadExcelWorkbook,
} from "@/lib/sales/excel-utils";
import {
  flattenGratuityByWaiterReportRows,
  type GratuityByWaiterReportMonth,
} from "@/lib/sales/gratuity-by-waiter-report";
import type { GratuityReportExportFormat } from "@/lib/sales/gratuity-report-export";

export type ExportGratuityByWaiterReportOptions = {
  venueName: string;
  venueLogoUrl?: string | null;
  report: GratuityByWaiterReportMonth;
  exportedAt: Date;
  userDisplayName: string;
};

type PdfLogoAsset = {
  dataUrl: string;
  format: "PNG" | "JPEG" | "WEBP";
  width: number;
  height: number;
};

const PDF_REPORT_TITLE = "Gratuity by Waiter Report";
const PDF_REPORT_SUBTITLE =
  "Daily cash and credit card gratuity by waiter from waiter sales";

const BRAND_DARK: [number, number, number] = [61, 66, 31];
const HEADER_BG: [number, number, number] = [240, 243, 221];
const TOTALS_BG: [number, number, number] = [226, 232, 200];
const FOOTER_TEXT: [number, number, number] = [120, 120, 120];

function sanitizeFilenamePart(value: string): string {
  return value
    .trim()
    .replace(/[\\/:*?"<>|]/g, "")
    .replace(/\s+/g, " ");
}

function formatExportDateStamp(date: Date): string {
  const day = String(date.getDate()).padStart(2, "0");
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const year = String(date.getFullYear()).slice(-2);
  return `${day}-${month}-${year}`;
}

function formatExportTimestamp(date: Date): string {
  const day = String(date.getDate()).padStart(2, "0");
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const year = date.getFullYear();
  const hours = String(date.getHours()).padStart(2, "0");
  const minutes = String(date.getMinutes()).padStart(2, "0");
  return `${day}/${month}/${year} ${hours}:${minutes}`;
}

function buildConfidentialityLine(
  exportedAt: Date,
  userDisplayName: string,
): string {
  const name = userDisplayName.trim() || "Unknown";
  return `File created on: ${formatExportTimestamp(exportedAt)} — Generated by ${name}   |   INTERNAL CONFIDENTIAL DOCUMENT   |   All rights reserved`;
}

export function buildGratuityByWaiterReportFilename(
  venueName: string,
  monthKey: string,
  format: GratuityReportExportFormat,
  exportedAt: Date = new Date(),
): string {
  const venue = sanitizeFilenamePart(venueName);
  const month = sanitizeFilenamePart(formatMonthLabel(monthKey));
  const stamp = formatExportDateStamp(exportedAt);
  const extension = format === "pdf" ? "pdf" : "xlsx";
  return `${venue} ${PDF_REPORT_TITLE} ${month} ${stamp}.${extension}`;
}

async function loadPdfLogoAsset(url: string): Promise<PdfLogoAsset | null> {
  if (typeof window === "undefined") return null;

  try {
    const response = await fetch(url);
    if (!response.ok) return null;

    const blob = await response.blob();

    if (blob.type.includes("svg") || url.endsWith(".svg")) {
      const svgText = await blob.text();
      const svgBlob = new Blob([svgText], {
        type: "image/svg+xml;charset=utf-8",
      });
      const objectUrl = URL.createObjectURL(svgBlob);

      try {
        return await new Promise<PdfLogoAsset | null>((resolve) => {
          const image = new Image();
          image.onload = () => {
            const canvas = document.createElement("canvas");
            canvas.width = image.naturalWidth || 400;
            canvas.height = image.naturalHeight || 400;
            const context = canvas.getContext("2d");
            URL.revokeObjectURL(objectUrl);

            if (!context) {
              resolve(null);
              return;
            }

            context.drawImage(image, 0, 0, canvas.width, canvas.height);
            resolve({
              dataUrl: canvas.toDataURL("image/png"),
              format: "PNG",
              width: canvas.width,
              height: canvas.height,
            });
          };
          image.onerror = () => {
            URL.revokeObjectURL(objectUrl);
            resolve(null);
          };
          image.src = objectUrl;
        });
      } catch {
        URL.revokeObjectURL(objectUrl);
        return null;
      }
    }

    const dataUrl = await new Promise<string>((resolve, reject) => {
      const reader = new FileReader();
      reader.onload = () => resolve(String(reader.result));
      reader.onerror = () => reject(reader.error);
      reader.readAsDataURL(blob);
    });

    const format = blob.type.includes("jpeg")
      ? "JPEG"
      : blob.type.includes("webp")
        ? "WEBP"
        : "PNG";

    return await new Promise<PdfLogoAsset | null>((resolve) => {
      const image = new Image();
      image.onload = () =>
        resolve({
          dataUrl,
          format,
          width: image.naturalWidth,
          height: image.naturalHeight,
        });
      image.onerror = () => resolve(null);
      image.src = dataUrl;
    });
  } catch {
    return null;
  }
}

function drawPageFooter(
  doc: jsPDF,
  options: ExportGratuityByWaiterReportOptions,
  marginLeft: number,
  marginRight: number,
): void {
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const footerY = pageHeight - 8;

  doc.setDrawColor(210, 210, 210);
  doc.setLineWidth(0.2);
  doc.line(marginLeft, footerY - 4, pageWidth - marginRight, footerY - 4);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(6.5);
  doc.setTextColor(...FOOTER_TEXT);
  doc.text(
    buildConfidentialityLine(options.exportedAt, options.userDisplayName),
    pageWidth / 2,
    footerY,
    { align: "center" },
  );
}

export async function exportGratuityByWaiterReportPdf(
  options: ExportGratuityByWaiterReportOptions,
): Promise<void> {
  const { venueName, venueLogoUrl, report } = options;
  const doc = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" });
  const marginLeft = 12;
  const marginRight = 12;
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 12;
  const flatRows = flattenGratuityByWaiterReportRows(report);

  const logo = venueLogoUrl ? await loadPdfLogoAsset(venueLogoUrl) : null;
  if (logo) {
    const logoHeight = 10;
    const logoWidth = Math.min(40, (logo.width / logo.height) * logoHeight);
    doc.addImage(
      logo.dataUrl,
      logo.format,
      marginLeft,
      y - 2,
      logoWidth,
      logoHeight,
      undefined,
      "FAST",
    );
  }

  doc.setFont("times", "bold");
  doc.setFontSize(16);
  doc.setTextColor(...BRAND_DARK);
  doc.text(PDF_REPORT_TITLE, pageWidth - marginRight, y + 2, {
    align: "right",
  });

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(95, 95, 95);
  doc.text(venueName, pageWidth - marginRight, y + 8, { align: "right" });
  doc.text(report.monthLabel, pageWidth - marginRight, y + 13, {
    align: "right",
  });

  y = 26;
  doc.setDrawColor(...BRAND_DARK);
  doc.setLineWidth(0.35);
  doc.line(marginLeft, y, pageWidth - marginRight, y);
  y += 6;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  doc.setTextColor(90, 90, 90);
  doc.text(PDF_REPORT_SUBTITLE, marginLeft, y);
  y += 6;

  autoTable(doc, {
    startY: y,
    margin: { left: marginLeft, right: marginRight, bottom: 16 },
    theme: "grid",
    styles: {
      fontSize: 7.5,
      cellPadding: 1.5,
      textColor: BRAND_DARK,
      lineColor: [210, 210, 200],
      lineWidth: 0.2,
    },
    headStyles: {
      fillColor: HEADER_BG,
      textColor: BRAND_DARK,
      fontStyle: "bold",
      halign: "center",
    },
    footStyles: {
      fillColor: TOTALS_BG,
      textColor: BRAND_DARK,
      fontStyle: "bold",
    },
    columnStyles: {
      0: { cellWidth: 28, halign: "left" },
      1: { cellWidth: 20, halign: "left" },
      2: { cellWidth: "auto", halign: "left" },
      3: { cellWidth: 32, halign: "right" },
      4: { cellWidth: 32, halign: "right" },
      5: { cellWidth: 32, halign: "right" },
    },
    head: [["Date", "Day", "Waiter", "Cash", "Credit Card", "Total"]],
    body: flatRows.map((row) => [
      formatDisplayDate(row.saleDate),
      row.weekDay,
      row.waiterName,
      formatMoney(row.cashGs),
      formatMoney(row.ccGs),
      formatMoney(row.totalGs),
    ]),
    foot: [
      [
        "Month total",
        `${report.summary.activeDayCount} day${report.summary.activeDayCount === 1 ? "" : "s"}`,
        `${report.summary.contributorCount} waiter${report.summary.contributorCount === 1 ? "" : "s"}`,
        formatMoney(report.summary.cashGs),
        formatMoney(report.summary.ccGs),
        formatMoney(report.summary.totalGs),
      ],
    ],
    didDrawPage: () => {
      drawPageFooter(doc, options, marginLeft, marginRight);
    },
  });

  doc.save(
    buildGratuityByWaiterReportFilename(
      venueName,
      report.monthKey,
      "pdf",
      options.exportedAt,
    ),
  );
}

export async function exportGratuityByWaiterReportExcel(
  options: ExportGratuityByWaiterReportOptions,
): Promise<void> {
  const { venueName, report, exportedAt, userDisplayName } = options;
  const flatRows = flattenGratuityByWaiterReportRows(report);

  const headers = ["Date", "Day", "Waiter", "Cash", "Credit Card", "Total"];
  const dataRows: (string | number)[][] = flatRows.map((row) => [
    formatDisplayDate(row.saleDate),
    row.weekDay,
    row.waiterName,
    row.cashGs,
    row.ccGs,
    row.totalGs,
  ]);

  dataRows.push([
    "Month total",
    `${report.summary.activeDayCount} day${report.summary.activeDayCount === 1 ? "" : "s"}`,
    `${report.summary.contributorCount} waiter${report.summary.contributorCount === 1 ? "" : "s"}`,
    report.summary.cashGs,
    report.summary.ccGs,
    report.summary.totalGs,
  ]);

  const workbook = await buildExcelWorkbook(
    "Gratuity by Waiter",
    headers,
    dataRows,
    [
      ["Gratuity by Waiter Report"],
      ["Venue", venueName],
      ["Month", report.monthLabel],
      ["Generated", formatExportTimestamp(exportedAt)],
      ["Generated by", userDisplayName],
      [],
      [
        "Daily cash and credit card gratuity by waiter from waiter sales entries.",
      ],
    ],
  );

  await downloadExcelWorkbook(
    workbook,
    buildGratuityByWaiterReportFilename(
      venueName,
      report.monthKey,
      "excel",
      exportedAt,
    ),
  );
}

export async function exportGratuityByWaiterReport(
  format: GratuityReportExportFormat,
  options: ExportGratuityByWaiterReportOptions,
): Promise<void> {
  if (format === "pdf") {
    await exportGratuityByWaiterReportPdf(options);
    return;
  }
  await exportGratuityByWaiterReportExcel(options);
}
