/**
 * Builds the "Generated by" label used in exported reports (PDFs).
 * Prefers "Name (email)" when a full name is available, otherwise falls back
 * to the email address, then a generic placeholder.
 */
export function buildExportUserLabel(
  fullName: string | null | undefined,
  email: string | null | undefined,
): string {
  const name = fullName?.trim();
  const mail = email?.trim();

  if (name && mail) return `${name} (${mail})`;
  return name || mail || "Unknown";
}
